package com.android.systemui.shade;

import android.content.ContentResolver;
import android.os.Handler;
import android.os.PowerManager;
import android.os.UserManager;
import android.view.LayoutInflater;
import android.view.accessibility.AccessibilityManager;
import com.android.internal.jank.InteractionJankMonitor;
import com.android.internal.logging.MetricsLogger;
import com.android.internal.util.LatencyTracker;
import com.android.keyguard.EmergencyButtonController;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.keyguard.SecLockIconViewController;
import com.android.keyguard.dagger.KeyguardQsUserSwitchComponent;
import com.android.keyguard.dagger.KeyguardStatusBarViewComponent;
import com.android.keyguard.dagger.KeyguardStatusViewComponent;
import com.android.keyguard.dagger.KeyguardUserSwitcherComponent;
import com.android.keyguard.punchhole.KeyguardPunchHoleVIViewController;
import com.android.systemui.biometrics.AuthController;
import com.android.systemui.classifier.FalsingCollector;
import com.android.systemui.doze.DozeLog;
import com.android.systemui.dump.DumpManager;
import com.android.systemui.flags.FeatureFlags;
import com.android.systemui.fragments.FragmentService;
import com.android.systemui.keyguard.KeyguardEditModeController;
import com.android.systemui.keyguard.KeyguardUnlockAnimationController;
import com.android.systemui.keyguard.animator.KeyguardTouchAnimator;
import com.android.systemui.keyguard.domain.interactor.AlternateBouncerInteractor;
import com.android.systemui.keyguard.domain.interactor.KeyguardBottomAreaInteractor;
import com.android.systemui.keyguard.domain.interactor.KeyguardFaceAuthInteractor;
import com.android.systemui.keyguard.domain.interactor.KeyguardInteractor;
import com.android.systemui.keyguard.domain.interactor.KeyguardTransitionInteractor;
import com.android.systemui.keyguard.ui.viewmodel.DreamingToLockscreenTransitionViewModel;
import com.android.systemui.keyguard.ui.viewmodel.GoneToDreamingTransitionViewModel;
import com.android.systemui.keyguard.ui.viewmodel.KeyguardBottomAreaViewModel;
import com.android.systemui.keyguard.ui.viewmodel.KeyguardLongPressViewModel;
import com.android.systemui.keyguard.ui.viewmodel.LockscreenToDreamingTransitionViewModel;
import com.android.systemui.keyguard.ui.viewmodel.LockscreenToOccludedTransitionViewModel;
import com.android.systemui.keyguard.ui.viewmodel.OccludedToLockscreenTransitionViewModel;
import com.android.systemui.keyguardimage.WallpaperImageInjectCreator;
import com.android.systemui.log.SecPanelLogger;
import com.android.systemui.media.controls.pipeline.MediaDataManager;
import com.android.systemui.media.controls.ui.KeyguardMediaController;
import com.android.systemui.model.SysUiState;
import com.android.systemui.navigationbar.NavigationBarController;
import com.android.systemui.navigationbar.NavigationModeController;
import com.android.systemui.pluginlock.PluginLockData;
import com.android.systemui.pluginlock.PluginLockMediator;
import com.android.systemui.plugins.ActivityStarter;
import com.android.systemui.plugins.FalsingManager;
import com.android.systemui.plugins.statusbar.StatusBarStateController;
import com.android.systemui.privacy.PrivacyDialogController;
import com.android.systemui.shade.transition.ShadeTransitionController;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.statusbar.KeyguardIndicationController;
import com.android.systemui.statusbar.LockscreenNotificationManager;
import com.android.systemui.statusbar.LockscreenShadeTransitionController;
import com.android.systemui.statusbar.NotificationShadeDepthController;
import com.android.systemui.statusbar.NotificationShadeWindowController;
import com.android.systemui.statusbar.NotificationShelfManager;
import com.android.systemui.statusbar.PulseExpansionHandler;
import com.android.systemui.statusbar.VibratorHelper;
import com.android.systemui.statusbar.iconsOnly.LockscreenNotificationIconsOnlyController;
import com.android.systemui.statusbar.notification.ConversationNotificationManager;
import com.android.systemui.statusbar.notification.DynamicPrivacyController;
import com.android.systemui.statusbar.notification.NotificationWakeUpCoordinator;
import com.android.systemui.statusbar.notification.row.NotificationGutsManager;
import com.android.systemui.statusbar.notification.stack.AmbientState;
import com.android.systemui.statusbar.notification.stack.NotificationListContainer;
import com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController;
import com.android.systemui.statusbar.notification.stack.NotificationStackSizeCalculator;
import com.android.systemui.statusbar.phone.DcmMascotViewContainer;
import com.android.systemui.statusbar.phone.DozeParameters;
import com.android.systemui.statusbar.phone.IndicatorTouchHandler;
import com.android.systemui.statusbar.phone.KeyguardBypassController;
import com.android.systemui.statusbar.phone.KeyguardClockPositionAlgorithm;
import com.android.systemui.statusbar.phone.LockscreenGestureLogger;
import com.android.systemui.statusbar.phone.ScreenOffAnimationController;
import com.android.systemui.statusbar.phone.ScrimController;
import com.android.systemui.statusbar.phone.StatusBarKeyguardViewManager;
import com.android.systemui.statusbar.phone.StatusBarTouchableRegionManager;
import com.android.systemui.statusbar.phone.TapAgainViewController;
import com.android.systemui.statusbar.phone.UnlockedScreenOffAnimationController;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.window.StatusBarWindowStateController;
import com.android.systemui.util.QsStatusEventLog;
import com.android.systemui.util.time.SystemClock;
import com.android.systemui.wallpaper.KeyguardWallpaperController;
import dagger.Lazy;
import dagger.internal.DoubleCheck;
import java.util.Optional;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;

/* compiled from: qb/87000731 7862a37e62df4d72b2921859baacdc80ea0c935793521606c8e11db53cc87e4f */
/* loaded from: classes2.dex */
public final class NotificationPanelViewController_Factory implements Provider {
    public final Provider accessibilityManagerProvider;
    public final Provider activityStarterProvider;
    public final Provider alternateBouncerInteractorProvider;
    public final Provider ambientStateProvider;
    public final Provider authControllerProvider;
    public final Provider bypassControllerProvider;
    public final Provider cameraLauncherLazyProvider;
    public final Provider clockPositionAlgorithmProvider;
    public final Provider commandQueueProvider;
    public final Provider configurationControllerProvider;
    public final Provider contentResolverProvider;
    public final Provider conversationNotificationManagerProvider;
    public final Provider coordinatorProvider;
    public final Provider coverScreenManagerLazyProvider;
    public final Provider dataUsageLabelManagerLazyProvider;
    public final Provider displayIdProvider;
    public final Provider dozeLogProvider;
    public final Provider dozeParametersProvider;
    public final Provider dreamingToLockscreenTransitionViewModelProvider;
    public final Provider dumpManagerProvider;
    public final Provider dynamicPrivacyControllerProvider;
    public final Provider editModeControllerProvider;
    public final Provider emergencyButtonControllerFactoryProvider;
    public final Provider falsingCollectorProvider;
    public final Provider falsingManagerProvider;
    public final Provider featureFlagsProvider;
    public final Provider flingAnimationUtilsBuilderProvider;
    public final Provider fragmentServiceProvider;
    public final Provider goneToDreamingTransitionViewModelProvider;
    public final Provider gutsManagerProvider;
    public final Provider handlerProvider;
    public final Provider indicatorTouchHandlerProvider;
    public final Provider interactionJankMonitorProvider;
    public final Provider keyguardBottomAreaInteractorProvider;
    public final Provider keyguardBottomAreaViewControllerProvider;
    public final Provider keyguardBottomAreaViewModelProvider;
    public final Provider keyguardFaceAuthInteractorProvider;
    public final Provider keyguardIndicationControllerProvider;
    public final Provider keyguardInteractorProvider;
    public final Provider keyguardLongPressViewModelProvider;
    public final Provider keyguardMediaControllerProvider;
    public final Provider keyguardQsUserSwitchComponentFactoryProvider;
    public final Provider keyguardStateControllerProvider;
    public final Provider keyguardStatusBarViewComponentFactoryProvider;
    public final Provider keyguardStatusViewComponentFactoryProvider;
    public final Provider keyguardTouchAnimatorProvider;
    public final Provider keyguardTransitionInteractorProvider;
    public final Provider keyguardUnlockAnimationControllerProvider;
    public final Provider keyguardUpdateMonitorProvider;
    public final Provider keyguardUserSwitcherComponentFactoryProvider;
    public final Provider keyguardWallpaperControllerProvider;
    public final Provider latencyTrackerProvider;
    public final Provider layoutInflaterProvider;
    public final Provider lockIconViewControllerProvider;
    public final Provider lockscreenGestureLoggerProvider;
    public final Provider lockscreenNotificationIconsOnlyControllerProvider;
    public final Provider lockscreenNotificationManagerProvider;
    public final Provider lockscreenShadeTransitionControllerProvider;
    public final Provider lockscreenToDreamingTransitionViewModelProvider;
    public final Provider lockscreenToOccludedTransitionViewModelProvider;
    public final Provider mBioUnlockControllerLazyProvider;
    public final Provider mainDispatcherProvider;
    public final Provider mascotViewContainerProvider;
    public final Provider mediaDataManagerProvider;
    public final Provider metricsLoggerProvider;
    public final Provider multiShadeInteractorProvider;
    public final Provider navigationBarControllerProvider;
    public final Provider navigationModeControllerProvider;
    public final Provider notificationListContainerProvider;
    public final Provider notificationShadeDepthControllerProvider;
    public final Provider notificationShadeWindowControllerProvider;
    public final Provider notificationShelfManagerProvider;
    public final Provider notificationStackScrollLayoutControllerProvider;
    public final Provider notificationStackSizeCalculatorProvider;
    public final Provider notificationsQSContainerControllerProvider;
    public final Provider occludedToLockscreenTransitionViewModelProvider;
    public final Provider panelLoggerProvider;
    public final Provider panelPolicyProvider;
    public final Provider pluginAODManagerLazyProvider;
    public final Provider pluginLockDataProvider;
    public final Provider pluginLockMediatorProvider;
    public final Provider pluginLockStarManagerLazyProvider;
    public final Provider powerManagerProvider;
    public final Provider privacyDialogControllerProvider;
    public final Provider pulseExpansionHandlerProvider;
    public final Provider punchHoleVIViewControllerFactoryProvider;
    public final Provider qsStatusEventLogProvider;
    public final Provider quickSettingsControllerProvider;
    public final Provider screenOffAnimationControllerProvider;
    public final Provider scrimControllerProvider;
    public final Provider shadeExpansionStateManagerProvider;
    public final Provider shadeHeaderControllerProvider;
    public final Provider shadeLoggerProvider;
    public final Provider shadeTransitionControllerProvider;
    public final Provider statusBarKeyguardViewManagerProvider;
    public final Provider statusBarStateControllerProvider;
    public final Provider statusBarTouchableRegionManagerProvider;
    public final Provider statusBarWindowStateControllerProvider;
    public final Provider subScreenManagerLazyProvider;
    public final Provider sysUiStateProvider;
    public final Provider systemClockProvider;
    public final Provider tapAgainViewControllerProvider;
    public final Provider unfoldComponentProvider;
    public final Provider unlockedScreenOffAnimationControllerProvider;
    public final Provider userManagerProvider;
    public final Provider vibratorHelperProvider;
    public final Provider viewProvider;
    public final Provider wallpaperImageCreatorProvider;

    public NotificationPanelViewController_Factory(Provider provider, Provider provider2, Provider provider3, Provider provider4, Provider provider5, Provider provider6, Provider provider7, Provider provider8, Provider provider9, Provider provider10, Provider provider11, Provider provider12, Provider provider13, Provider provider14, Provider provider15, Provider provider16, Provider provider17, Provider provider18, Provider provider19, Provider provider20, Provider provider21, Provider provider22, Provider provider23, Provider provider24, Provider provider25, Provider provider26, Provider provider27, Provider provider28, Provider provider29, Provider provider30, Provider provider31, Provider provider32, Provider provider33, Provider provider34, Provider provider35, Provider provider36, Provider provider37, Provider provider38, Provider provider39, Provider provider40, Provider provider41, Provider provider42, Provider provider43, Provider provider44, Provider provider45, Provider provider46, Provider provider47, Provider provider48, Provider provider49, Provider provider50, Provider provider51, Provider provider52, Provider provider53, Provider provider54, Provider provider55, Provider provider56, Provider provider57, Provider provider58, Provider provider59, Provider provider60, Provider provider61, Provider provider62, Provider provider63, Provider provider64, Provider provider65, Provider provider66, Provider provider67, Provider provider68, Provider provider69, Provider provider70, Provider provider71, Provider provider72, Provider provider73, Provider provider74, Provider provider75, Provider provider76, Provider provider77, Provider provider78, Provider provider79, Provider provider80, Provider provider81, Provider provider82, Provider provider83, Provider provider84, Provider provider85, Provider provider86, Provider provider87, Provider provider88, Provider provider89, Provider provider90, Provider provider91, Provider provider92, Provider provider93, Provider provider94, Provider provider95, Provider provider96, Provider provider97, Provider provider98, Provider provider99, Provider provider100, Provider provider101, Provider provider102, Provider provider103, Provider provider104, Provider provider105, Provider provider106, Provider provider107, Provider provider108) {
        this.mascotViewContainerProvider = provider;
        this.pluginLockMediatorProvider = provider2;
        this.pluginLockDataProvider = provider3;
        this.clockPositionAlgorithmProvider = provider4;
        this.pluginAODManagerLazyProvider = provider5;
        this.viewProvider = provider6;
        this.handlerProvider = provider7;
        this.layoutInflaterProvider = provider8;
        this.featureFlagsProvider = provider9;
        this.coordinatorProvider = provider10;
        this.pulseExpansionHandlerProvider = provider11;
        this.dynamicPrivacyControllerProvider = provider12;
        this.bypassControllerProvider = provider13;
        this.falsingManagerProvider = provider14;
        this.falsingCollectorProvider = provider15;
        this.keyguardStateControllerProvider = provider16;
        this.statusBarStateControllerProvider = provider17;
        this.statusBarWindowStateControllerProvider = provider18;
        this.notificationShadeWindowControllerProvider = provider19;
        this.dozeLogProvider = provider20;
        this.dozeParametersProvider = provider21;
        this.commandQueueProvider = provider22;
        this.vibratorHelperProvider = provider23;
        this.latencyTrackerProvider = provider24;
        this.powerManagerProvider = provider25;
        this.accessibilityManagerProvider = provider26;
        this.displayIdProvider = provider27;
        this.keyguardUpdateMonitorProvider = provider28;
        this.metricsLoggerProvider = provider29;
        this.shadeLoggerProvider = provider30;
        this.configurationControllerProvider = provider31;
        this.flingAnimationUtilsBuilderProvider = provider32;
        this.statusBarTouchableRegionManagerProvider = provider33;
        this.conversationNotificationManagerProvider = provider34;
        this.statusBarKeyguardViewManagerProvider = provider35;
        this.gutsManagerProvider = provider36;
        this.notificationsQSContainerControllerProvider = provider37;
        this.notificationStackScrollLayoutControllerProvider = provider38;
        this.keyguardStatusViewComponentFactoryProvider = provider39;
        this.keyguardQsUserSwitchComponentFactoryProvider = provider40;
        this.keyguardUserSwitcherComponentFactoryProvider = provider41;
        this.keyguardStatusBarViewComponentFactoryProvider = provider42;
        this.lockscreenShadeTransitionControllerProvider = provider43;
        this.authControllerProvider = provider44;
        this.scrimControllerProvider = provider45;
        this.userManagerProvider = provider46;
        this.mediaDataManagerProvider = provider47;
        this.notificationShadeDepthControllerProvider = provider48;
        this.ambientStateProvider = provider49;
        this.lockIconViewControllerProvider = provider50;
        this.keyguardMediaControllerProvider = provider51;
        this.tapAgainViewControllerProvider = provider52;
        this.navigationModeControllerProvider = provider53;
        this.navigationBarControllerProvider = provider54;
        this.quickSettingsControllerProvider = provider55;
        this.fragmentServiceProvider = provider56;
        this.contentResolverProvider = provider57;
        this.shadeHeaderControllerProvider = provider58;
        this.screenOffAnimationControllerProvider = provider59;
        this.lockscreenGestureLoggerProvider = provider60;
        this.shadeExpansionStateManagerProvider = provider61;
        this.unfoldComponentProvider = provider62;
        this.sysUiStateProvider = provider63;
        this.keyguardBottomAreaViewControllerProvider = provider64;
        this.keyguardUnlockAnimationControllerProvider = provider65;
        this.keyguardIndicationControllerProvider = provider66;
        this.notificationListContainerProvider = provider67;
        this.notificationStackSizeCalculatorProvider = provider68;
        this.unlockedScreenOffAnimationControllerProvider = provider69;
        this.shadeTransitionControllerProvider = provider70;
        this.interactionJankMonitorProvider = provider71;
        this.systemClockProvider = provider72;
        this.keyguardBottomAreaViewModelProvider = provider73;
        this.keyguardBottomAreaInteractorProvider = provider74;
        this.cameraLauncherLazyProvider = provider75;
        this.alternateBouncerInteractorProvider = provider76;
        this.dreamingToLockscreenTransitionViewModelProvider = provider77;
        this.occludedToLockscreenTransitionViewModelProvider = provider78;
        this.lockscreenToDreamingTransitionViewModelProvider = provider79;
        this.goneToDreamingTransitionViewModelProvider = provider80;
        this.lockscreenToOccludedTransitionViewModelProvider = provider81;
        this.mainDispatcherProvider = provider82;
        this.keyguardTransitionInteractorProvider = provider83;
        this.multiShadeInteractorProvider = provider84;
        this.dumpManagerProvider = provider85;
        this.keyguardLongPressViewModelProvider = provider86;
        this.keyguardInteractorProvider = provider87;
        this.activityStarterProvider = provider88;
        this.keyguardFaceAuthInteractorProvider = provider89;
        this.notificationShelfManagerProvider = provider90;
        this.privacyDialogControllerProvider = provider91;
        this.punchHoleVIViewControllerFactoryProvider = provider92;
        this.keyguardTouchAnimatorProvider = provider93;
        this.editModeControllerProvider = provider94;
        this.dataUsageLabelManagerLazyProvider = provider95;
        this.indicatorTouchHandlerProvider = provider96;
        this.qsStatusEventLogProvider = provider97;
        this.lockscreenNotificationManagerProvider = provider98;
        this.lockscreenNotificationIconsOnlyControllerProvider = provider99;
        this.keyguardWallpaperControllerProvider = provider100;
        this.wallpaperImageCreatorProvider = provider101;
        this.emergencyButtonControllerFactoryProvider = provider102;
        this.panelLoggerProvider = provider103;
        this.panelPolicyProvider = provider104;
        this.subScreenManagerLazyProvider = provider105;
        this.coverScreenManagerLazyProvider = provider106;
        this.pluginLockStarManagerLazyProvider = provider107;
        this.mBioUnlockControllerLazyProvider = provider108;
    }

    public static NotificationPanelViewController newInstance(DcmMascotViewContainer dcmMascotViewContainer, PluginLockMediator pluginLockMediator, PluginLockData pluginLockData, KeyguardClockPositionAlgorithm keyguardClockPositionAlgorithm, Lazy lazy, NotificationPanelView notificationPanelView, Handler handler, LayoutInflater layoutInflater, FeatureFlags featureFlags, NotificationWakeUpCoordinator notificationWakeUpCoordinator, PulseExpansionHandler pulseExpansionHandler, DynamicPrivacyController dynamicPrivacyController, KeyguardBypassController keyguardBypassController, FalsingManager falsingManager, FalsingCollector falsingCollector, KeyguardStateController keyguardStateController, StatusBarStateController statusBarStateController, StatusBarWindowStateController statusBarWindowStateController, NotificationShadeWindowController notificationShadeWindowController, DozeLog dozeLog, DozeParameters dozeParameters, CommandQueue commandQueue, VibratorHelper vibratorHelper, LatencyTracker latencyTracker, PowerManager powerManager, AccessibilityManager accessibilityManager, int i, KeyguardUpdateMonitor keyguardUpdateMonitor, MetricsLogger metricsLogger, ShadeLogger shadeLogger, ConfigurationController configurationController, Provider provider, StatusBarTouchableRegionManager statusBarTouchableRegionManager, ConversationNotificationManager conversationNotificationManager, StatusBarKeyguardViewManager statusBarKeyguardViewManager, NotificationGutsManager notificationGutsManager, NotificationsQSContainerController notificationsQSContainerController, NotificationStackScrollLayoutController notificationStackScrollLayoutController, KeyguardStatusViewComponent.Factory factory, KeyguardQsUserSwitchComponent.Factory factory2, KeyguardUserSwitcherComponent.Factory factory3, KeyguardStatusBarViewComponent.Factory factory4, LockscreenShadeTransitionController lockscreenShadeTransitionController, AuthController authController, ScrimController scrimController, UserManager userManager, MediaDataManager mediaDataManager, NotificationShadeDepthController notificationShadeDepthController, AmbientState ambientState, SecLockIconViewController secLockIconViewController, KeyguardMediaController keyguardMediaController, TapAgainViewController tapAgainViewController, NavigationModeController navigationModeController, NavigationBarController navigationBarController, QuickSettingsController quickSettingsController, FragmentService fragmentService, ContentResolver contentResolver, ShadeHeaderController shadeHeaderController, ScreenOffAnimationController screenOffAnimationController, LockscreenGestureLogger lockscreenGestureLogger, ShadeExpansionStateManager shadeExpansionStateManager, Optional optional, SysUiState sysUiState, Provider provider2, KeyguardUnlockAnimationController keyguardUnlockAnimationController, KeyguardIndicationController keyguardIndicationController, NotificationListContainer notificationListContainer, NotificationStackSizeCalculator notificationStackSizeCalculator, UnlockedScreenOffAnimationController unlockedScreenOffAnimationController, ShadeTransitionController shadeTransitionController, InteractionJankMonitor interactionJankMonitor, SystemClock systemClock, KeyguardBottomAreaViewModel keyguardBottomAreaViewModel, KeyguardBottomAreaInteractor keyguardBottomAreaInteractor, Lazy lazy2, AlternateBouncerInteractor alternateBouncerInteractor, DreamingToLockscreenTransitionViewModel dreamingToLockscreenTransitionViewModel, OccludedToLockscreenTransitionViewModel occludedToLockscreenTransitionViewModel, LockscreenToDreamingTransitionViewModel lockscreenToDreamingTransitionViewModel, GoneToDreamingTransitionViewModel goneToDreamingTransitionViewModel, LockscreenToOccludedTransitionViewModel lockscreenToOccludedTransitionViewModel, CoroutineDispatcher coroutineDispatcher, KeyguardTransitionInteractor keyguardTransitionInteractor, Provider provider3, DumpManager dumpManager, KeyguardLongPressViewModel keyguardLongPressViewModel, KeyguardInteractor keyguardInteractor, ActivityStarter activityStarter, KeyguardFaceAuthInteractor keyguardFaceAuthInteractor, NotificationShelfManager notificationShelfManager, PrivacyDialogController privacyDialogController, KeyguardPunchHoleVIViewController.Factory factory5, KeyguardTouchAnimator keyguardTouchAnimator, KeyguardEditModeController keyguardEditModeController, Lazy lazy3, IndicatorTouchHandler indicatorTouchHandler, QsStatusEventLog qsStatusEventLog, LockscreenNotificationManager lockscreenNotificationManager, LockscreenNotificationIconsOnlyController lockscreenNotificationIconsOnlyController, KeyguardWallpaperController keyguardWallpaperController, WallpaperImageInjectCreator wallpaperImageInjectCreator, EmergencyButtonController.Factory factory6, SecPanelLogger secPanelLogger, SecPanelPolicy secPanelPolicy, Lazy lazy4, Lazy lazy5, Lazy lazy6) {
        return new NotificationPanelViewController(dcmMascotViewContainer, pluginLockMediator, pluginLockData, keyguardClockPositionAlgorithm, lazy, notificationPanelView, handler, layoutInflater, featureFlags, notificationWakeUpCoordinator, pulseExpansionHandler, dynamicPrivacyController, keyguardBypassController, falsingManager, falsingCollector, keyguardStateController, statusBarStateController, statusBarWindowStateController, notificationShadeWindowController, dozeLog, dozeParameters, commandQueue, vibratorHelper, latencyTracker, powerManager, accessibilityManager, i, keyguardUpdateMonitor, metricsLogger, shadeLogger, configurationController, provider, statusBarTouchableRegionManager, conversationNotificationManager, statusBarKeyguardViewManager, notificationGutsManager, notificationsQSContainerController, notificationStackScrollLayoutController, factory, factory2, factory3, factory4, lockscreenShadeTransitionController, authController, scrimController, userManager, mediaDataManager, notificationShadeDepthController, ambientState, secLockIconViewController, keyguardMediaController, tapAgainViewController, navigationModeController, navigationBarController, quickSettingsController, fragmentService, contentResolver, shadeHeaderController, screenOffAnimationController, lockscreenGestureLogger, shadeExpansionStateManager, optional, sysUiState, provider2, keyguardUnlockAnimationController, keyguardIndicationController, notificationListContainer, notificationStackSizeCalculator, unlockedScreenOffAnimationController, shadeTransitionController, interactionJankMonitor, systemClock, keyguardBottomAreaViewModel, keyguardBottomAreaInteractor, lazy2, alternateBouncerInteractor, dreamingToLockscreenTransitionViewModel, occludedToLockscreenTransitionViewModel, lockscreenToDreamingTransitionViewModel, goneToDreamingTransitionViewModel, lockscreenToOccludedTransitionViewModel, coroutineDispatcher, keyguardTransitionInteractor, provider3, dumpManager, keyguardLongPressViewModel, keyguardInteractor, activityStarter, keyguardFaceAuthInteractor, notificationShelfManager, privacyDialogController, factory5, keyguardTouchAnimator, keyguardEditModeController, lazy3, indicatorTouchHandler, qsStatusEventLog, lockscreenNotificationManager, lockscreenNotificationIconsOnlyController, keyguardWallpaperController, wallpaperImageInjectCreator, factory6, secPanelLogger, secPanelPolicy, lazy4, lazy5, lazy6);
    }

    @Override // javax.inject.Provider
    public final Object get() {
        NotificationPanelViewController newInstance = newInstance((DcmMascotViewContainer) this.mascotViewContainerProvider.get(), (PluginLockMediator) this.pluginLockMediatorProvider.get(), (PluginLockData) this.pluginLockDataProvider.get(), (KeyguardClockPositionAlgorithm) this.clockPositionAlgorithmProvider.get(), DoubleCheck.lazy(this.pluginAODManagerLazyProvider), (NotificationPanelView) this.viewProvider.get(), (Handler) this.handlerProvider.get(), (LayoutInflater) this.layoutInflaterProvider.get(), (FeatureFlags) this.featureFlagsProvider.get(), (NotificationWakeUpCoordinator) this.coordinatorProvider.get(), (PulseExpansionHandler) this.pulseExpansionHandlerProvider.get(), (DynamicPrivacyController) this.dynamicPrivacyControllerProvider.get(), (KeyguardBypassController) this.bypassControllerProvider.get(), (FalsingManager) this.falsingManagerProvider.get(), (FalsingCollector) this.falsingCollectorProvider.get(), (KeyguardStateController) this.keyguardStateControllerProvider.get(), (StatusBarStateController) this.statusBarStateControllerProvider.get(), (StatusBarWindowStateController) this.statusBarWindowStateControllerProvider.get(), (NotificationShadeWindowController) this.notificationShadeWindowControllerProvider.get(), (DozeLog) this.dozeLogProvider.get(), (DozeParameters) this.dozeParametersProvider.get(), (CommandQueue) this.commandQueueProvider.get(), (VibratorHelper) this.vibratorHelperProvider.get(), (LatencyTracker) this.latencyTrackerProvider.get(), (PowerManager) this.powerManagerProvider.get(), (AccessibilityManager) this.accessibilityManagerProvider.get(), ((Integer) this.displayIdProvider.get()).intValue(), (KeyguardUpdateMonitor) this.keyguardUpdateMonitorProvider.get(), (MetricsLogger) this.metricsLoggerProvider.get(), (ShadeLogger) this.shadeLoggerProvider.get(), (ConfigurationController) this.configurationControllerProvider.get(), this.flingAnimationUtilsBuilderProvider, (StatusBarTouchableRegionManager) this.statusBarTouchableRegionManagerProvider.get(), (ConversationNotificationManager) this.conversationNotificationManagerProvider.get(), (StatusBarKeyguardViewManager) this.statusBarKeyguardViewManagerProvider.get(), (NotificationGutsManager) this.gutsManagerProvider.get(), (NotificationsQSContainerController) this.notificationsQSContainerControllerProvider.get(), (NotificationStackScrollLayoutController) this.notificationStackScrollLayoutControllerProvider.get(), (KeyguardStatusViewComponent.Factory) this.keyguardStatusViewComponentFactoryProvider.get(), (KeyguardQsUserSwitchComponent.Factory) this.keyguardQsUserSwitchComponentFactoryProvider.get(), (KeyguardUserSwitcherComponent.Factory) this.keyguardUserSwitcherComponentFactoryProvider.get(), (KeyguardStatusBarViewComponent.Factory) this.keyguardStatusBarViewComponentFactoryProvider.get(), (LockscreenShadeTransitionController) this.lockscreenShadeTransitionControllerProvider.get(), (AuthController) this.authControllerProvider.get(), (ScrimController) this.scrimControllerProvider.get(), (UserManager) this.userManagerProvider.get(), (MediaDataManager) this.mediaDataManagerProvider.get(), (NotificationShadeDepthController) this.notificationShadeDepthControllerProvider.get(), (AmbientState) this.ambientStateProvider.get(), (SecLockIconViewController) this.lockIconViewControllerProvider.get(), (KeyguardMediaController) this.keyguardMediaControllerProvider.get(), (TapAgainViewController) this.tapAgainViewControllerProvider.get(), (NavigationModeController) this.navigationModeControllerProvider.get(), (NavigationBarController) this.navigationBarControllerProvider.get(), (QuickSettingsController) this.quickSettingsControllerProvider.get(), (FragmentService) this.fragmentServiceProvider.get(), (ContentResolver) this.contentResolverProvider.get(), (ShadeHeaderController) this.shadeHeaderControllerProvider.get(), (ScreenOffAnimationController) this.screenOffAnimationControllerProvider.get(), (LockscreenGestureLogger) this.lockscreenGestureLoggerProvider.get(), (ShadeExpansionStateManager) this.shadeExpansionStateManagerProvider.get(), (Optional) this.unfoldComponentProvider.get(), (SysUiState) this.sysUiStateProvider.get(), this.keyguardBottomAreaViewControllerProvider, (KeyguardUnlockAnimationController) this.keyguardUnlockAnimationControllerProvider.get(), (KeyguardIndicationController) this.keyguardIndicationControllerProvider.get(), (NotificationListContainer) this.notificationListContainerProvider.get(), (NotificationStackSizeCalculator) this.notificationStackSizeCalculatorProvider.get(), (UnlockedScreenOffAnimationController) this.unlockedScreenOffAnimationControllerProvider.get(), (ShadeTransitionController) this.shadeTransitionControllerProvider.get(), (InteractionJankMonitor) this.interactionJankMonitorProvider.get(), (SystemClock) this.systemClockProvider.get(), (KeyguardBottomAreaViewModel) this.keyguardBottomAreaViewModelProvider.get(), (KeyguardBottomAreaInteractor) this.keyguardBottomAreaInteractorProvider.get(), DoubleCheck.lazy(this.cameraLauncherLazyProvider), (AlternateBouncerInteractor) this.alternateBouncerInteractorProvider.get(), (DreamingToLockscreenTransitionViewModel) this.dreamingToLockscreenTransitionViewModelProvider.get(), (OccludedToLockscreenTransitionViewModel) this.occludedToLockscreenTransitionViewModelProvider.get(), (LockscreenToDreamingTransitionViewModel) this.lockscreenToDreamingTransitionViewModelProvider.get(), (GoneToDreamingTransitionViewModel) this.goneToDreamingTransitionViewModelProvider.get(), (LockscreenToOccludedTransitionViewModel) this.lockscreenToOccludedTransitionViewModelProvider.get(), (CoroutineDispatcher) this.mainDispatcherProvider.get(), (KeyguardTransitionInteractor) this.keyguardTransitionInteractorProvider.get(), this.multiShadeInteractorProvider, (DumpManager) this.dumpManagerProvider.get(), (KeyguardLongPressViewModel) this.keyguardLongPressViewModelProvider.get(), (KeyguardInteractor) this.keyguardInteractorProvider.get(), (ActivityStarter) this.activityStarterProvider.get(), (KeyguardFaceAuthInteractor) this.keyguardFaceAuthInteractorProvider.get(), (NotificationShelfManager) this.notificationShelfManagerProvider.get(), (PrivacyDialogController) this.privacyDialogControllerProvider.get(), (KeyguardPunchHoleVIViewController.Factory) this.punchHoleVIViewControllerFactoryProvider.get(), (KeyguardTouchAnimator) this.keyguardTouchAnimatorProvider.get(), (KeyguardEditModeController) this.editModeControllerProvider.get(), DoubleCheck.lazy(this.dataUsageLabelManagerLazyProvider), (IndicatorTouchHandler) this.indicatorTouchHandlerProvider.get(), (QsStatusEventLog) this.qsStatusEventLogProvider.get(), (LockscreenNotificationManager) this.lockscreenNotificationManagerProvider.get(), (LockscreenNotificationIconsOnlyController) this.lockscreenNotificationIconsOnlyControllerProvider.get(), (KeyguardWallpaperController) this.keyguardWallpaperControllerProvider.get(), (WallpaperImageInjectCreator) this.wallpaperImageCreatorProvider.get(), (EmergencyButtonController.Factory) this.emergencyButtonControllerFactoryProvider.get(), (SecPanelLogger) this.panelLoggerProvider.get(), (SecPanelPolicy) this.panelPolicyProvider.get(), DoubleCheck.lazy(this.subScreenManagerLazyProvider), DoubleCheck.lazy(this.coverScreenManagerLazyProvider), DoubleCheck.lazy(this.pluginLockStarManagerLazyProvider));
        DoubleCheck.lazy(this.mBioUnlockControllerLazyProvider);
        return newInstance;
    }
}
