package com.android.internal.telephony;

/* loaded from: classes5.dex */
public class SemTelephonyIntents {
    public static final String ACTION_AUDIO_RECEIVER_SAR = "android.samsung.media.action.receiver_sar";
    public static final String ACTION_CAMERA_START = "com.sec.android.app.camera.ACTION_CAMERA_START";
    public static final String ACTION_CAMERA_STOP = "com.sec.android.app.camera.ACTION_CAMERA_STOP";
    public static final String ACTION_CONTEXT_AWARE_HEADSET = "com.sec.android.contextaware.HEADSET_PLUG";
    public static final String ACTION_GCF_DEVICE_STORAGE_LOW = "android.intent.action.GCF_DEVICE_STORAGE_LOW";
    public static final String ACTION_GCF_DEVICE_STORAGE_OK = "android.intent.action.GCF_DEVICE_STORAGE_OK";
    public static final String ACTION_HDMI_PLUGGED = "android.intent.action.HDMI_PLUGGED";
    public static final String ACTION_KTLBS_DATA_SMS_RECEIVED = "com.kt.location.action.KTLBS_DATA_SMS_RECEIVED";
    public static final String ACTION_KT_TWO_PHONE_MANAGE_SMS_RECEIVED = "com.kt.menu.action.TWO_CALL_REG_CHANGED";
    public static final String ACTION_SEM_CARRIER_CHANGED = "com.samsung.carrier.action.CARRIER_CHANGED";
    public static final String ACTION_USB_OTG_CONNECTION = "com.samsung.UsbOtgCableConnection";
    public static final String CB_SETTINGS_AVAILABLE_ACTION = "com.samsung.provider.Telephony.CB_SETTINGS_AVAILABLE";
    public static final String DIRECTED_SMS_RECEIVED_ACTION = "verizon.intent.action.DIRECTED_SMS_RECEIVED";
    public static final String DISH_WAP_PUSH_SL_ACTION = "com.sec.unifiedwfc.action.WAP_PUSH_SL";
    public static final String EXTRA_SEM_CARRIER_CHANGED_CID = "com.samsung.carrier.extra.CARRIER_CANONICAL_ID";
    public static final String EXTRA_SEM_CARRIER_CHANGED_GROUP_CHANGED = "com.samsung.carrier.extra.CARRIER_GROUP_CHANGED";
    public static final String EXTRA_SEM_CARRIER_CHANGED_PHONE_ID = "com.samsung.carrier.extra.CARRIER_PHONE_ID";
    public static final String EXTRA_SEM_CARRIER_CHANGED_STATE = "com.samsung.carrier.extra.CARRIER_STATE";
    public static final String EXTRA_VALUE_RECEIVER_SAR = "android.samsung.media.extra.receiver";
    public static final String GET_SMSC_ACTION = "com.samsung.provider.Telephony.GET_SMSC";
    public static final String IMEI_TRACKER_SMS_RECEIVED_ACTION = "com.samsung.provider.Telephony.IMEI_TRACKER_SMS_RECEIVED";
    public static final String LGU_APM_RECEIVED_ACTION = "android.lgt.action.APM_SMS_RECEIVED";
    public static final String LGU_DETECT_EMERGENCY_STATE = "com.lgt.action.DETECT_EMERGENCY_STATE";
    public static final String LGU_FOTA_RECEIVED_ACTION = "com.samsung.intent.action.PUSH_CONFIRM";
    public static final String LMS_FIRST_DISPLAY_TIMEOUT_CTC_ACTION = "com.samsung.provider.Telephony.LMS_FIRST_DISPLAY_TIMEOUT_CTC";
    public static final String LMS_MAXIMAL_CONNECTION_TIMEOUT_CTC_ACTION = "com.samsung.provider.Telephony.LMS_MAXIMAL_CONNECTION_TIMEOUT_CTC";
    public static final String NSRISMS_RECEIVED_ACTION = "com.samsung.provider.Telephony.SECURITY_SMS_RECEIVED";
    public static final String SEM_ACTION_BIG_DATA_INFO = "com.samsung.intent.action.BIG_DATA_INFO";
    public static final String SEM_ACTION_CALL_STATE_CHANGED = "com.sec.action.CALL_STATE_CHANGED";
    public static final String SEM_ACTION_CHAMELEON_TELEPHONY_UPDATE = "android.intent.action.CHAMELEON_TELEPHONY_UPDATE";
    public static final String SEM_ACTION_CURRENT_TTY_MODE_CHANGED_2 = "com.samsung.android.telecom.action.CURRENT_TTY_MODE_CHANGED_2";
    public static final String SEM_ACTION_DEVICE_CONFIG_UPDATED = "com.samsung.nsds.action.DEVICE_CONFIG_UPDATED";
    public static final String SEM_ACTION_DRX_BACK_TO_DEFAULT = "com.samsung.intent.action.ACTION_DRX_BACK_TO_DEFAULT";
    public static final String SEM_ACTION_ELEVATOR_MODE_START = "com.samsung.android.intent.action.elevator_mode_start";
    public static final String SEM_ACTION_ICON_UW_DSQ_CHANGED = "com.samsung.telephony.event.EVENT_ICON_UW_DSQ_CHANGED";
    public static final String SEM_ACTION_IMEI_STATE_CHANGED = "com.samsung.intent.action.IMEI_STATE_CHANGED";
    public static final String SEM_ACTION_MANUAL_SET_TIME = "com.samsung.android.intent.action.MANUAL_SET_TIME";
    public static final String SEM_ACTION_MOCK_CELL = "com.samsung.intent.action.ACTION_MOCK_CELL";
    public static final String SEM_ACTION_NETWORK_REJECT_INDI = "com.samsung.android.app.telephonyui.action.REJECT_FOR_TRANSFER";
    public static final String SEM_ACTION_OPEN_NET_SETTINGS = "com.samsung.android.app.telephonyui.action.OPEN_NET_SETTINGS";
    public static final String SEM_ACTION_TPLMN_BARRING = "com.samsung.intent.action.tplmn_barring";
    public static final String SEM_ACTION_TTY_PREFERRED_MODE_CHANGED_2 = "com.samsung.android.telecom.action.TTY_PREFERRED_MODE_CHANGED_2";
    public static final String SEM_ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW = "android.intent.action.ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW";
    public static final String SEM_INTENT_CS_DIAGNOSIS = "com.samsung.android.mobiledoctor.GETAPMDATAFILES";
    public static final String SEM_PROVIDER_DATA_ACTIVITY_CHANGE = "com.verizon.provider.DATA_ACTIVITY_CHANGE";
    public static final String SHOW_DATA_SMS_RECEIVED_ACTION = "com.kt.show.manger.action.SHOW_DATA_SMS_RECEIVED";
    public static final String WAP_PUSH_DM_NOTI_RECEIVED_ACTION = "com.samsung.provider.Telephony.WAP_PUSH_DM_NOTI_RECEIVED";
    public static final String WAP_PUSH_DS_NOTI_RECEIVED_ACTION = "com.samsung.provider.Telephony.WAP_PUSH_DS_NOTI_RECEIVED";
}
