package com.android.systemui.statusbar.phone;

import android.app.WallpaperManager;
import android.content.Context;
import android.hardware.devicestate.DeviceStateManager;
import android.os.Handler;
import android.os.PowerManager;
import android.service.dreams.IDreamManager;
import android.util.DisplayMetrics;
import com.android.internal.jank.InteractionJankMonitor;
import com.android.internal.logging.MetricsLogger;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.keyguard.ViewMediatorCallback;
import com.android.systemui.InitController;
import com.android.systemui.accessibility.floatingmenu.AccessibilityFloatingMenuController;
import com.android.systemui.animation.ActivityLaunchAnimator;
import com.android.systemui.aod.AODAmbientWallpaperHelper;
import com.android.systemui.biometrics.AuthRippleController;
import com.android.systemui.bixby2.SystemUICommandActionHandler;
import com.android.systemui.blur.SecQpBlurController;
import com.android.systemui.broadcast.BroadcastDispatcher;
import com.android.systemui.charging.WiredChargingRippleController;
import com.android.systemui.classifier.FalsingCollector;
import com.android.systemui.colorextraction.SysuiColorExtractor;
import com.android.systemui.demomode.DemoModeController;
import com.android.systemui.flags.FeatureFlags;
import com.android.systemui.fragments.FragmentService;
import com.android.systemui.keyguard.DisplayLifecycle;
import com.android.systemui.keyguard.KeyguardSysDumpTrigger;
import com.android.systemui.keyguard.KeyguardUnlockAnimationController;
import com.android.systemui.keyguard.KeyguardViewMediator;
import com.android.systemui.keyguard.ScreenLifecycle;
import com.android.systemui.keyguard.WakefulnessLifecycle;
import com.android.systemui.keyguard.domain.interactor.AlternateBouncerInteractor;
import com.android.systemui.log.SecPanelLogger;
import com.android.systemui.mdm.MdmOverlayContainer;
import com.android.systemui.navigationbar.NavigationBarController;
import com.android.systemui.plugins.ActivityStarter;
import com.android.systemui.plugins.FalsingManager;
import com.android.systemui.plugins.PluginDependencyProvider;
import com.android.systemui.plugins.PluginManager;
import com.android.systemui.popup.SamsungScreenPinningRequest;
import com.android.systemui.recents.ScreenPinningRequest;
import com.android.systemui.settings.UserTracker;
import com.android.systemui.settings.brightness.BrightnessSliderController;
import com.android.systemui.shade.ShadeController;
import com.android.systemui.shade.ShadeExpansionStateManager;
import com.android.systemui.shade.ShadeLogger;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.statusbar.KeyguardIndicationController;
import com.android.systemui.statusbar.LightRevealScrim;
import com.android.systemui.statusbar.LockscreenShadeTransitionController;
import com.android.systemui.statusbar.NotificationLockscreenUserManager;
import com.android.systemui.statusbar.NotificationMediaManager;
import com.android.systemui.statusbar.NotificationRemoteInputManager;
import com.android.systemui.statusbar.NotificationShadeWindowController;
import com.android.systemui.statusbar.PulseExpansionHandler;
import com.android.systemui.statusbar.SecLightRevealScrimHelper;
import com.android.systemui.statusbar.SysuiStatusBarStateController;
import com.android.systemui.statusbar.core.StatusBarInitializer;
import com.android.systemui.statusbar.notification.DynamicPrivacyController;
import com.android.systemui.statusbar.notification.NotificationWakeUpCoordinator;
import com.android.systemui.statusbar.notification.collection.notifcollection.CommonNotifCollection;
import com.android.systemui.statusbar.notification.init.NotificationsController;
import com.android.systemui.statusbar.notification.interruption.NotificationInterruptStateProvider;
import com.android.systemui.statusbar.notification.logging.NotificationLogger;
import com.android.systemui.statusbar.notification.row.NotifRemoteViewCache;
import com.android.systemui.statusbar.notification.row.NotificationGutsManager;
import com.android.systemui.statusbar.phone.dagger.CentralSurfacesComponent;
import com.android.systemui.statusbar.phone.ongoingcall.OngoingCallController;
import com.android.systemui.statusbar.policy.BatteryController;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.policy.DeviceProvisionedController;
import com.android.systemui.statusbar.policy.ExtensionController;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.policy.UserInfoControllerImpl;
import com.android.systemui.statusbar.policy.UserSwitcherController;
import com.android.systemui.statusbar.window.StatusBarWindowController;
import com.android.systemui.statusbar.window.StatusBarWindowStateController;
import com.android.systemui.util.WallpaperController;
import com.android.systemui.util.concurrency.DelayableExecutor;
import com.android.systemui.util.concurrency.MessageRouter;
import com.android.systemui.volume.VolumeComponent;
import com.android.systemui.wallpaper.KeyguardWallpaper;
import dagger.Lazy;
import dagger.internal.DoubleCheck;
import java.util.Optional;
import java.util.concurrent.Executor;
import javax.inject.Provider;

/* compiled from: qb/87000731 7862a37e62df4d72b2921859baacdc80ea0c935793521606c8e11db53cc87e4f */
/* loaded from: classes2.dex */
public final class CentralSurfacesImpl_Factory implements Provider {
    public final Provider accessibilityFloatingMenuControllerProvider;
    public final Provider activityLaunchAnimatorProvider;
    public final Provider activityStarterProvider;
    public final Provider alternateBouncerInteractorProvider;
    public final Provider assistManagerLazyProvider;
    public final Provider authRippleControllerProvider;
    public final Provider autoHideControllerProvider;
    public final Provider batteryControllerProvider;
    public final Provider biometricUnlockControllerLazyProvider;
    public final Provider brightnessSliderFactoryProvider;
    public final Provider broadcastDispatcherProvider;
    public final Provider bubblesOptionalProvider;
    public final Provider cameraLauncherLazyProvider;
    public final Provider centralSurfacesComponentFactoryProvider;
    public final Provider colorExtractorProvider;
    public final Provider commandQueueProvider;
    public final Provider configurationControllerProvider;
    public final Provider contextProvider;
    public final Provider coverHostLazyProvider;
    public final Provider delayableExecutorProvider;
    public final Provider demoModeControllerProvider;
    public final Provider deviceProvisionedControllerProvider;
    public final Provider deviceStateManagerProvider;
    public final Provider displayLifecycleProvider;
    public final Provider displayMetricsProvider;
    public final Provider dozeParametersProvider;
    public final Provider dozeScrimControllerProvider;
    public final Provider dozeServiceHostProvider;
    public final Provider dreamManagerProvider;
    public final Provider dynamicPrivacyControllerProvider;
    public final Provider extensionControllerProvider;
    public final Provider falsingCollectorProvider;
    public final Provider falsingManagerProvider;
    public final Provider featureFlagsProvider;
    public final Provider fingerprintManagerProvider;
    public final Provider fragmentServiceProvider;
    public final Provider headsUpManagerPhoneProvider;
    public final Provider initControllerProvider;
    public final Provider jankMonitorProvider;
    public final Provider keyguardBypassControllerProvider;
    public final Provider keyguardDismissUtilProvider;
    public final Provider keyguardIndicationControllerProvider;
    public final Provider keyguardStateControllerProvider;
    public final Provider keyguardSurfaceControllerLazyProvider;
    public final Provider keyguardUnlockAnimationControllerProvider;
    public final Provider keyguardUpdateMonitorProvider;
    public final Provider keyguardViewMediatorProvider;
    public final Provider keyguardWallpaperProvider;
    public final Provider lightBarControllerProvider;
    public final Provider lightRevealScrimProvider;
    public final Provider lightRevealScrimViewModelLazyProvider;
    public final Provider lockScreenUserManagerProvider;
    public final Provider lockscreenShadeTransitionControllerProvider;
    public final Provider lockscreenWallpaperLazyProvider;
    public final Provider mAODAmbientWallpaperHelperProvider;
    public final Provider mPluginAODManagerLazyProvider;
    public final Provider mSecLightRevealScrimHelperProvider;
    public final Provider mainHandlerProvider;
    public final Provider mdmOverlayContainerProvider;
    public final Provider messageRouterProvider;
    public final Provider metricsLoggerProvider;
    public final Provider navBarHelperLazyProvider;
    public final Provider navigationBarControllerProvider;
    public final Provider noteTaskControllerLazyProvider;
    public final Provider notifCollectionProvider;
    public final Provider notifRemoteViewCacheProvider;
    public final Provider notificationGutsManagerProvider;
    public final Provider notificationIconAreaControllerProvider;
    public final Provider notificationInterruptStateProvider;
    public final Provider notificationLoggerProvider;
    public final Provider notificationMediaManagerProvider;
    public final Provider notificationShadeDepthControllerLazyProvider;
    public final Provider notificationShadeWindowControllerProvider;
    public final Provider notificationWakeUpCoordinatorProvider;
    public final Provider notificationsControllerProvider;
    public final Provider ongoingCallControllerProvider;
    public final Provider panelLoggerProvider;
    public final Provider phoneStatusBarPolicyProvider;
    public final Provider pluginDependencyProvider;
    public final Provider pluginManagerProvider;
    public final Provider powerManagerProvider;
    public final Provider pulseExpansionHandlerProvider;
    public final Provider remoteInputManagerProvider;
    public final Provider samsungScreenPinningRequestProvider;
    public final Provider samsungStatusBarGrayIconHelperProvider;
    public final Provider screenLifecycleProvider;
    public final Provider screenOffAnimationControllerProvider;
    public final Provider screenPinningRequestProvider;
    public final Provider scrimControllerProvider;
    public final Provider secQpBlurControllerProvider;
    public final Provider shadeControllerProvider;
    public final Provider shadeExpansionStateManagerProvider;
    public final Provider shadeLoggerProvider;
    public final Provider startingSurfaceOptionalProvider;
    public final Provider statusBarHideIconsForBouncerManagerProvider;
    public final Provider statusBarInitializerProvider;
    public final Provider statusBarKeyguardViewManagerProvider;
    public final Provider statusBarSignalPolicyProvider;
    public final Provider statusBarStateControllerProvider;
    public final Provider statusBarTouchableRegionManagerProvider;
    public final Provider statusBarWindowControllerProvider;
    public final Provider statusBarWindowStateControllerProvider;
    public final Provider sysDumpTriggerProvider;
    public final Provider systemUICommandActionHandlerProvider;
    public final Provider timeTickHandlerProvider;
    public final Provider uiBgExecutorProvider;
    public final Provider userInfoControllerImplProvider;
    public final Provider userSwitcherControllerProvider;
    public final Provider userTrackerProvider;
    public final Provider viewMediatorCallbackProvider;
    public final Provider volumeComponentProvider;
    public final Provider wakefulnessLifecycleProvider;
    public final Provider wallpaperControllerProvider;
    public final Provider wallpaperManagerProvider;
    public final Provider wiredChargingRippleControllerProvider;

    public CentralSurfacesImpl_Factory(Provider provider, Provider provider2, Provider provider3, Provider provider4, Provider provider5, Provider provider6, Provider provider7, Provider provider8, Provider provider9, Provider provider10, Provider provider11, Provider provider12, Provider provider13, Provider provider14, Provider provider15, Provider provider16, Provider provider17, Provider provider18, Provider provider19, Provider provider20, Provider provider21, Provider provider22, Provider provider23, Provider provider24, Provider provider25, Provider provider26, Provider provider27, Provider provider28, Provider provider29, Provider provider30, Provider provider31, Provider provider32, Provider provider33, Provider provider34, Provider provider35, Provider provider36, Provider provider37, Provider provider38, Provider provider39, Provider provider40, Provider provider41, Provider provider42, Provider provider43, Provider provider44, Provider provider45, Provider provider46, Provider provider47, Provider provider48, Provider provider49, Provider provider50, Provider provider51, Provider provider52, Provider provider53, Provider provider54, Provider provider55, Provider provider56, Provider provider57, Provider provider58, Provider provider59, Provider provider60, Provider provider61, Provider provider62, Provider provider63, Provider provider64, Provider provider65, Provider provider66, Provider provider67, Provider provider68, Provider provider69, Provider provider70, Provider provider71, Provider provider72, Provider provider73, Provider provider74, Provider provider75, Provider provider76, Provider provider77, Provider provider78, Provider provider79, Provider provider80, Provider provider81, Provider provider82, Provider provider83, Provider provider84, Provider provider85, Provider provider86, Provider provider87, Provider provider88, Provider provider89, Provider provider90, Provider provider91, Provider provider92, Provider provider93, Provider provider94, Provider provider95, Provider provider96, Provider provider97, Provider provider98, Provider provider99, Provider provider100, Provider provider101, Provider provider102, Provider provider103, Provider provider104, Provider provider105, Provider provider106, Provider provider107, Provider provider108, Provider provider109, Provider provider110, Provider provider111, Provider provider112, Provider provider113, Provider provider114, Provider provider115) {
        this.sysDumpTriggerProvider = provider;
        this.mdmOverlayContainerProvider = provider2;
        this.mainHandlerProvider = provider3;
        this.displayLifecycleProvider = provider4;
        this.keyguardWallpaperProvider = provider5;
        this.systemUICommandActionHandlerProvider = provider6;
        this.coverHostLazyProvider = provider7;
        this.keyguardSurfaceControllerLazyProvider = provider8;
        this.samsungStatusBarGrayIconHelperProvider = provider9;
        this.contextProvider = provider10;
        this.notificationsControllerProvider = provider11;
        this.fragmentServiceProvider = provider12;
        this.lightBarControllerProvider = provider13;
        this.autoHideControllerProvider = provider14;
        this.statusBarInitializerProvider = provider15;
        this.statusBarWindowControllerProvider = provider16;
        this.statusBarWindowStateControllerProvider = provider17;
        this.keyguardUpdateMonitorProvider = provider18;
        this.statusBarSignalPolicyProvider = provider19;
        this.pulseExpansionHandlerProvider = provider20;
        this.notificationWakeUpCoordinatorProvider = provider21;
        this.keyguardBypassControllerProvider = provider22;
        this.keyguardStateControllerProvider = provider23;
        this.headsUpManagerPhoneProvider = provider24;
        this.dynamicPrivacyControllerProvider = provider25;
        this.falsingManagerProvider = provider26;
        this.falsingCollectorProvider = provider27;
        this.broadcastDispatcherProvider = provider28;
        this.notificationGutsManagerProvider = provider29;
        this.notificationLoggerProvider = provider30;
        this.notificationInterruptStateProvider = provider31;
        this.shadeExpansionStateManagerProvider = provider32;
        this.keyguardViewMediatorProvider = provider33;
        this.displayMetricsProvider = provider34;
        this.metricsLoggerProvider = provider35;
        this.shadeLoggerProvider = provider36;
        this.uiBgExecutorProvider = provider37;
        this.notificationMediaManagerProvider = provider38;
        this.lockScreenUserManagerProvider = provider39;
        this.remoteInputManagerProvider = provider40;
        this.userSwitcherControllerProvider = provider41;
        this.batteryControllerProvider = provider42;
        this.colorExtractorProvider = provider43;
        this.screenLifecycleProvider = provider44;
        this.wakefulnessLifecycleProvider = provider45;
        this.statusBarStateControllerProvider = provider46;
        this.bubblesOptionalProvider = provider47;
        this.noteTaskControllerLazyProvider = provider48;
        this.deviceProvisionedControllerProvider = provider49;
        this.navigationBarControllerProvider = provider50;
        this.accessibilityFloatingMenuControllerProvider = provider51;
        this.assistManagerLazyProvider = provider52;
        this.configurationControllerProvider = provider53;
        this.notificationShadeWindowControllerProvider = provider54;
        this.dozeParametersProvider = provider55;
        this.scrimControllerProvider = provider56;
        this.lockscreenWallpaperLazyProvider = provider57;
        this.biometricUnlockControllerLazyProvider = provider58;
        this.authRippleControllerProvider = provider59;
        this.dozeServiceHostProvider = provider60;
        this.powerManagerProvider = provider61;
        this.screenPinningRequestProvider = provider62;
        this.samsungScreenPinningRequestProvider = provider63;
        this.dozeScrimControllerProvider = provider64;
        this.volumeComponentProvider = provider65;
        this.commandQueueProvider = provider66;
        this.centralSurfacesComponentFactoryProvider = provider67;
        this.pluginManagerProvider = provider68;
        this.shadeControllerProvider = provider69;
        this.statusBarKeyguardViewManagerProvider = provider70;
        this.viewMediatorCallbackProvider = provider71;
        this.initControllerProvider = provider72;
        this.timeTickHandlerProvider = provider73;
        this.pluginDependencyProvider = provider74;
        this.keyguardDismissUtilProvider = provider75;
        this.extensionControllerProvider = provider76;
        this.userInfoControllerImplProvider = provider77;
        this.phoneStatusBarPolicyProvider = provider78;
        this.keyguardIndicationControllerProvider = provider79;
        this.demoModeControllerProvider = provider80;
        this.notificationShadeDepthControllerLazyProvider = provider81;
        this.statusBarTouchableRegionManagerProvider = provider82;
        this.notificationIconAreaControllerProvider = provider83;
        this.brightnessSliderFactoryProvider = provider84;
        this.screenOffAnimationControllerProvider = provider85;
        this.wallpaperControllerProvider = provider86;
        this.ongoingCallControllerProvider = provider87;
        this.statusBarHideIconsForBouncerManagerProvider = provider88;
        this.lockscreenShadeTransitionControllerProvider = provider89;
        this.featureFlagsProvider = provider90;
        this.keyguardUnlockAnimationControllerProvider = provider91;
        this.delayableExecutorProvider = provider92;
        this.messageRouterProvider = provider93;
        this.wallpaperManagerProvider = provider94;
        this.startingSurfaceOptionalProvider = provider95;
        this.activityLaunchAnimatorProvider = provider96;
        this.jankMonitorProvider = provider97;
        this.deviceStateManagerProvider = provider98;
        this.wiredChargingRippleControllerProvider = provider99;
        this.dreamManagerProvider = provider100;
        this.cameraLauncherLazyProvider = provider101;
        this.lightRevealScrimViewModelLazyProvider = provider102;
        this.lightRevealScrimProvider = provider103;
        this.alternateBouncerInteractorProvider = provider104;
        this.userTrackerProvider = provider105;
        this.fingerprintManagerProvider = provider106;
        this.activityStarterProvider = provider107;
        this.navBarHelperLazyProvider = provider108;
        this.secQpBlurControllerProvider = provider109;
        this.notifRemoteViewCacheProvider = provider110;
        this.notifCollectionProvider = provider111;
        this.panelLoggerProvider = provider112;
        this.mSecLightRevealScrimHelperProvider = provider113;
        this.mAODAmbientWallpaperHelperProvider = provider114;
        this.mPluginAODManagerLazyProvider = provider115;
    }

    public static CentralSurfacesImpl newInstance(KeyguardSysDumpTrigger keyguardSysDumpTrigger, MdmOverlayContainer mdmOverlayContainer, Handler handler, DisplayLifecycle displayLifecycle, KeyguardWallpaper keyguardWallpaper, SystemUICommandActionHandler systemUICommandActionHandler, Lazy lazy, Lazy lazy2, SamsungStatusBarGrayIconHelper samsungStatusBarGrayIconHelper, Context context, NotificationsController notificationsController, FragmentService fragmentService, LightBarController lightBarController, AutoHideController autoHideController, StatusBarInitializer statusBarInitializer, StatusBarWindowController statusBarWindowController, StatusBarWindowStateController statusBarWindowStateController, KeyguardUpdateMonitor keyguardUpdateMonitor, StatusBarSignalPolicy statusBarSignalPolicy, PulseExpansionHandler pulseExpansionHandler, NotificationWakeUpCoordinator notificationWakeUpCoordinator, KeyguardBypassController keyguardBypassController, KeyguardStateController keyguardStateController, HeadsUpManagerPhone headsUpManagerPhone, DynamicPrivacyController dynamicPrivacyController, FalsingManager falsingManager, FalsingCollector falsingCollector, BroadcastDispatcher broadcastDispatcher, NotificationGutsManager notificationGutsManager, NotificationLogger notificationLogger, NotificationInterruptStateProvider notificationInterruptStateProvider, ShadeExpansionStateManager shadeExpansionStateManager, KeyguardViewMediator keyguardViewMediator, DisplayMetrics displayMetrics, MetricsLogger metricsLogger, ShadeLogger shadeLogger, Executor executor, NotificationMediaManager notificationMediaManager, NotificationLockscreenUserManager notificationLockscreenUserManager, NotificationRemoteInputManager notificationRemoteInputManager, UserSwitcherController userSwitcherController, BatteryController batteryController, SysuiColorExtractor sysuiColorExtractor, ScreenLifecycle screenLifecycle, WakefulnessLifecycle wakefulnessLifecycle, SysuiStatusBarStateController sysuiStatusBarStateController, Optional optional, Lazy lazy3, DeviceProvisionedController deviceProvisionedController, NavigationBarController navigationBarController, AccessibilityFloatingMenuController accessibilityFloatingMenuController, Lazy lazy4, ConfigurationController configurationController, NotificationShadeWindowController notificationShadeWindowController, DozeParameters dozeParameters, ScrimController scrimController, Lazy lazy5, Lazy lazy6, AuthRippleController authRippleController, DozeServiceHost dozeServiceHost, PowerManager powerManager, ScreenPinningRequest screenPinningRequest, SamsungScreenPinningRequest samsungScreenPinningRequest, DozeScrimController dozeScrimController, VolumeComponent volumeComponent, CommandQueue commandQueue, CentralSurfacesComponent.Factory factory, PluginManager pluginManager, ShadeController shadeController, StatusBarKeyguardViewManager statusBarKeyguardViewManager, ViewMediatorCallback viewMediatorCallback, InitController initController, Handler handler2, PluginDependencyProvider pluginDependencyProvider, KeyguardDismissUtil keyguardDismissUtil, ExtensionController extensionController, UserInfoControllerImpl userInfoControllerImpl, PhoneStatusBarPolicy phoneStatusBarPolicy, KeyguardIndicationController keyguardIndicationController, DemoModeController demoModeController, Lazy lazy7, StatusBarTouchableRegionManager statusBarTouchableRegionManager, NotificationIconAreaController notificationIconAreaController, BrightnessSliderController.Factory factory2, ScreenOffAnimationController screenOffAnimationController, WallpaperController wallpaperController, OngoingCallController ongoingCallController, StatusBarHideIconsForBouncerManager statusBarHideIconsForBouncerManager, LockscreenShadeTransitionController lockscreenShadeTransitionController, FeatureFlags featureFlags, KeyguardUnlockAnimationController keyguardUnlockAnimationController, DelayableExecutor delayableExecutor, MessageRouter messageRouter, WallpaperManager wallpaperManager, Optional optional2, ActivityLaunchAnimator activityLaunchAnimator, InteractionJankMonitor interactionJankMonitor, DeviceStateManager deviceStateManager, WiredChargingRippleController wiredChargingRippleController, IDreamManager iDreamManager, Lazy lazy8, Lazy lazy9, LightRevealScrim lightRevealScrim, AlternateBouncerInteractor alternateBouncerInteractor, UserTracker userTracker, Provider provider, ActivityStarter activityStarter, Lazy lazy10, SecQpBlurController secQpBlurController, NotifRemoteViewCache notifRemoteViewCache, CommonNotifCollection commonNotifCollection, SecPanelLogger secPanelLogger) {
        return new CentralSurfacesImpl(keyguardSysDumpTrigger, mdmOverlayContainer, handler, displayLifecycle, keyguardWallpaper, systemUICommandActionHandler, lazy, lazy2, samsungStatusBarGrayIconHelper, context, notificationsController, fragmentService, lightBarController, autoHideController, statusBarInitializer, statusBarWindowController, statusBarWindowStateController, keyguardUpdateMonitor, statusBarSignalPolicy, pulseExpansionHandler, notificationWakeUpCoordinator, keyguardBypassController, keyguardStateController, headsUpManagerPhone, dynamicPrivacyController, falsingManager, falsingCollector, broadcastDispatcher, notificationGutsManager, notificationLogger, notificationInterruptStateProvider, shadeExpansionStateManager, keyguardViewMediator, displayMetrics, metricsLogger, shadeLogger, executor, notificationMediaManager, notificationLockscreenUserManager, notificationRemoteInputManager, userSwitcherController, batteryController, sysuiColorExtractor, screenLifecycle, wakefulnessLifecycle, sysuiStatusBarStateController, optional, lazy3, deviceProvisionedController, navigationBarController, accessibilityFloatingMenuController, lazy4, configurationController, notificationShadeWindowController, dozeParameters, scrimController, lazy5, lazy6, authRippleController, dozeServiceHost, powerManager, screenPinningRequest, samsungScreenPinningRequest, dozeScrimController, volumeComponent, commandQueue, factory, pluginManager, shadeController, statusBarKeyguardViewManager, viewMediatorCallback, initController, handler2, pluginDependencyProvider, keyguardDismissUtil, extensionController, userInfoControllerImpl, phoneStatusBarPolicy, keyguardIndicationController, demoModeController, lazy7, statusBarTouchableRegionManager, notificationIconAreaController, factory2, screenOffAnimationController, wallpaperController, ongoingCallController, statusBarHideIconsForBouncerManager, lockscreenShadeTransitionController, featureFlags, keyguardUnlockAnimationController, delayableExecutor, messageRouter, wallpaperManager, optional2, activityLaunchAnimator, interactionJankMonitor, deviceStateManager, wiredChargingRippleController, iDreamManager, lazy8, lazy9, lightRevealScrim, alternateBouncerInteractor, userTracker, provider, activityStarter, lazy10, secQpBlurController, notifRemoteViewCache, commonNotifCollection, secPanelLogger);
    }

    @Override // javax.inject.Provider
    public final Object get() {
        CentralSurfacesImpl newInstance = newInstance((KeyguardSysDumpTrigger) this.sysDumpTriggerProvider.get(), (MdmOverlayContainer) this.mdmOverlayContainerProvider.get(), (Handler) this.mainHandlerProvider.get(), (DisplayLifecycle) this.displayLifecycleProvider.get(), (KeyguardWallpaper) this.keyguardWallpaperProvider.get(), (SystemUICommandActionHandler) this.systemUICommandActionHandlerProvider.get(), DoubleCheck.lazy(this.coverHostLazyProvider), DoubleCheck.lazy(this.keyguardSurfaceControllerLazyProvider), (SamsungStatusBarGrayIconHelper) this.samsungStatusBarGrayIconHelperProvider.get(), (Context) this.contextProvider.get(), (NotificationsController) this.notificationsControllerProvider.get(), (FragmentService) this.fragmentServiceProvider.get(), (LightBarController) this.lightBarControllerProvider.get(), (AutoHideController) this.autoHideControllerProvider.get(), (StatusBarInitializer) this.statusBarInitializerProvider.get(), (StatusBarWindowController) this.statusBarWindowControllerProvider.get(), (StatusBarWindowStateController) this.statusBarWindowStateControllerProvider.get(), (KeyguardUpdateMonitor) this.keyguardUpdateMonitorProvider.get(), (StatusBarSignalPolicy) this.statusBarSignalPolicyProvider.get(), (PulseExpansionHandler) this.pulseExpansionHandlerProvider.get(), (NotificationWakeUpCoordinator) this.notificationWakeUpCoordinatorProvider.get(), (KeyguardBypassController) this.keyguardBypassControllerProvider.get(), (KeyguardStateController) this.keyguardStateControllerProvider.get(), (HeadsUpManagerPhone) this.headsUpManagerPhoneProvider.get(), (DynamicPrivacyController) this.dynamicPrivacyControllerProvider.get(), (FalsingManager) this.falsingManagerProvider.get(), (FalsingCollector) this.falsingCollectorProvider.get(), (BroadcastDispatcher) this.broadcastDispatcherProvider.get(), (NotificationGutsManager) this.notificationGutsManagerProvider.get(), (NotificationLogger) this.notificationLoggerProvider.get(), (NotificationInterruptStateProvider) this.notificationInterruptStateProvider.get(), (ShadeExpansionStateManager) this.shadeExpansionStateManagerProvider.get(), (KeyguardViewMediator) this.keyguardViewMediatorProvider.get(), (DisplayMetrics) this.displayMetricsProvider.get(), (MetricsLogger) this.metricsLoggerProvider.get(), (ShadeLogger) this.shadeLoggerProvider.get(), (Executor) this.uiBgExecutorProvider.get(), (NotificationMediaManager) this.notificationMediaManagerProvider.get(), (NotificationLockscreenUserManager) this.lockScreenUserManagerProvider.get(), (NotificationRemoteInputManager) this.remoteInputManagerProvider.get(), (UserSwitcherController) this.userSwitcherControllerProvider.get(), (BatteryController) this.batteryControllerProvider.get(), (SysuiColorExtractor) this.colorExtractorProvider.get(), (ScreenLifecycle) this.screenLifecycleProvider.get(), (WakefulnessLifecycle) this.wakefulnessLifecycleProvider.get(), (SysuiStatusBarStateController) this.statusBarStateControllerProvider.get(), (Optional) this.bubblesOptionalProvider.get(), DoubleCheck.lazy(this.noteTaskControllerLazyProvider), (DeviceProvisionedController) this.deviceProvisionedControllerProvider.get(), (NavigationBarController) this.navigationBarControllerProvider.get(), (AccessibilityFloatingMenuController) this.accessibilityFloatingMenuControllerProvider.get(), DoubleCheck.lazy(this.assistManagerLazyProvider), (ConfigurationController) this.configurationControllerProvider.get(), (NotificationShadeWindowController) this.notificationShadeWindowControllerProvider.get(), (DozeParameters) this.dozeParametersProvider.get(), (ScrimController) this.scrimControllerProvider.get(), DoubleCheck.lazy(this.lockscreenWallpaperLazyProvider), DoubleCheck.lazy(this.biometricUnlockControllerLazyProvider), (AuthRippleController) this.authRippleControllerProvider.get(), (DozeServiceHost) this.dozeServiceHostProvider.get(), (PowerManager) this.powerManagerProvider.get(), (ScreenPinningRequest) this.screenPinningRequestProvider.get(), (SamsungScreenPinningRequest) this.samsungScreenPinningRequestProvider.get(), (DozeScrimController) this.dozeScrimControllerProvider.get(), (VolumeComponent) this.volumeComponentProvider.get(), (CommandQueue) this.commandQueueProvider.get(), (CentralSurfacesComponent.Factory) this.centralSurfacesComponentFactoryProvider.get(), (PluginManager) this.pluginManagerProvider.get(), (ShadeController) this.shadeControllerProvider.get(), (StatusBarKeyguardViewManager) this.statusBarKeyguardViewManagerProvider.get(), (ViewMediatorCallback) this.viewMediatorCallbackProvider.get(), (InitController) this.initControllerProvider.get(), (Handler) this.timeTickHandlerProvider.get(), (PluginDependencyProvider) this.pluginDependencyProvider.get(), (KeyguardDismissUtil) this.keyguardDismissUtilProvider.get(), (ExtensionController) this.extensionControllerProvider.get(), (UserInfoControllerImpl) this.userInfoControllerImplProvider.get(), (PhoneStatusBarPolicy) this.phoneStatusBarPolicyProvider.get(), (KeyguardIndicationController) this.keyguardIndicationControllerProvider.get(), (DemoModeController) this.demoModeControllerProvider.get(), DoubleCheck.lazy(this.notificationShadeDepthControllerLazyProvider), (StatusBarTouchableRegionManager) this.statusBarTouchableRegionManagerProvider.get(), (NotificationIconAreaController) this.notificationIconAreaControllerProvider.get(), (BrightnessSliderController.Factory) this.brightnessSliderFactoryProvider.get(), (ScreenOffAnimationController) this.screenOffAnimationControllerProvider.get(), (WallpaperController) this.wallpaperControllerProvider.get(), (OngoingCallController) this.ongoingCallControllerProvider.get(), (StatusBarHideIconsForBouncerManager) this.statusBarHideIconsForBouncerManagerProvider.get(), (LockscreenShadeTransitionController) this.lockscreenShadeTransitionControllerProvider.get(), (FeatureFlags) this.featureFlagsProvider.get(), (KeyguardUnlockAnimationController) this.keyguardUnlockAnimationControllerProvider.get(), (DelayableExecutor) this.delayableExecutorProvider.get(), (MessageRouter) this.messageRouterProvider.get(), (WallpaperManager) this.wallpaperManagerProvider.get(), (Optional) this.startingSurfaceOptionalProvider.get(), (ActivityLaunchAnimator) this.activityLaunchAnimatorProvider.get(), (InteractionJankMonitor) this.jankMonitorProvider.get(), (DeviceStateManager) this.deviceStateManagerProvider.get(), (WiredChargingRippleController) this.wiredChargingRippleControllerProvider.get(), (IDreamManager) this.dreamManagerProvider.get(), DoubleCheck.lazy(this.cameraLauncherLazyProvider), DoubleCheck.lazy(this.lightRevealScrimViewModelLazyProvider), (LightRevealScrim) this.lightRevealScrimProvider.get(), (AlternateBouncerInteractor) this.alternateBouncerInteractorProvider.get(), (UserTracker) this.userTrackerProvider.get(), this.fingerprintManagerProvider, (ActivityStarter) this.activityStarterProvider.get(), DoubleCheck.lazy(this.navBarHelperLazyProvider), (SecQpBlurController) this.secQpBlurControllerProvider.get(), (NotifRemoteViewCache) this.notifRemoteViewCacheProvider.get(), (CommonNotifCollection) this.notifCollectionProvider.get(), (SecPanelLogger) this.panelLoggerProvider.get());
        newInstance.mSecLightRevealScrimHelper = (SecLightRevealScrimHelper) this.mSecLightRevealScrimHelperProvider.get();
        newInstance.mAODAmbientWallpaperHelper = (AODAmbientWallpaperHelper) this.mAODAmbientWallpaperHelperProvider.get();
        DoubleCheck.lazy(this.mPluginAODManagerLazyProvider);
        return newInstance;
    }
}
