package com.android.settingslib.mobile;

import com.android.settingslib.SignalIcon$MobileIconGroup;
import com.android.systemui.R;
import com.sec.ims.settings.ImsProfile;
import java.util.HashMap;
import java.util.Map;

/* compiled from: qb/87000731 7862a37e62df4d72b2921859baacdc80ea0c935793521606c8e11db53cc87e4f */
/* loaded from: classes.dex */
public final class TelephonyIcons {
    public static final SignalIcon$MobileIconGroup CARRIER_MERGED_WIFI;
    public static final SignalIcon$MobileIconGroup CARRIER_NETWORK_CHANGE;
    public static final SignalIcon$MobileIconGroup DATA_DISABLED;
    public static final SignalIcon$MobileIconGroup E;
    public static final SignalIcon$MobileIconGroup E_CHN;
    public static final SignalIcon$MobileIconGroup E_VZW;
    public static final SignalIcon$MobileIconGroup FOUR_G;
    public static final SignalIcon$MobileIconGroup FOUR_G_ATT;
    public static final SignalIcon$MobileIconGroup FOUR_G_CHN;
    public static final SignalIcon$MobileIconGroup FOUR_G_LTE;
    public static final SignalIcon$MobileIconGroup FOUR_G_LTE_LTN;
    public static final SignalIcon$MobileIconGroup FOUR_G_LTE_PLUS;
    public static final SignalIcon$MobileIconGroup FOUR_G_PLUS;
    public static final SignalIcon$MobileIconGroup FOUR_G_PLUS_CHN;
    public static final SignalIcon$MobileIconGroup FOUR_G_TMO;
    public static final SignalIcon$MobileIconGroup FOUR_G_USC;
    public static final SignalIcon$MobileIconGroup FOUR_G_VZW;
    public static final SignalIcon$MobileIconGroup FOUR_HALF_G;
    public static final SignalIcon$MobileIconGroup FOUR_HALF_G_AMX;
    public static final SignalIcon$MobileIconGroup FOUR_HALF_G_PLUS_AMX;
    public static final SignalIcon$MobileIconGroup G;
    public static final SignalIcon$MobileIconGroup G_CHN;
    public static final SignalIcon$MobileIconGroup G_VZW;
    public static final SignalIcon$MobileIconGroup H;
    public static final SignalIcon$MobileIconGroup H_CHN;
    public static final SignalIcon$MobileIconGroup H_PLUS;
    public static final SignalIcon$MobileIconGroup H_PLUS_CHN;
    public static final SignalIcon$MobileIconGroup H_PLUS_VZW;
    public static final SignalIcon$MobileIconGroup H_VZW;
    public static final Map ICON_NAME_TO_ICON;
    public static final SignalIcon$MobileIconGroup LTE;
    public static final SignalIcon$MobileIconGroup LTE_ATT;
    public static final SignalIcon$MobileIconGroup LTE_CA_5G_E;
    public static final SignalIcon$MobileIconGroup LTE_KT;
    public static final SignalIcon$MobileIconGroup LTE_PLUS;
    public static final SignalIcon$MobileIconGroup LTE_PLUS_KT;
    public static final SignalIcon$MobileIconGroup LTE_TMO;
    public static final int[] MOBILE_CALL_STRENGTH_ICONS;
    public static final int[] MOBILE_DATA_ACTIVITY_ICONS;
    public static final SignalIcon$MobileIconGroup NOT_DEFAULT_DATA;
    public static final SignalIcon$MobileIconGroup NR_5G;
    public static final SignalIcon$MobileIconGroup NR_5GA_CHN;
    public static final SignalIcon$MobileIconGroup NR_5G_ATT;
    public static final SignalIcon$MobileIconGroup NR_5G_AVAILABLE;
    public static final SignalIcon$MobileIconGroup NR_5G_AVAILABLE_KT;
    public static final SignalIcon$MobileIconGroup NR_5G_CHN;
    public static final SignalIcon$MobileIconGroup NR_5G_CONNECTED;
    public static final SignalIcon$MobileIconGroup NR_5G_CONNECTED_KT;
    public static final SignalIcon$MobileIconGroup NR_5G_CONNECTED_PLUS;
    public static final SignalIcon$MobileIconGroup NR_5G_ENLARGED_PLUS;
    public static final SignalIcon$MobileIconGroup NR_5G_E_ATT;
    public static final SignalIcon$MobileIconGroup NR_5G_PLUS;
    public static final SignalIcon$MobileIconGroup NR_5G_PLUS_ATT;
    public static final SignalIcon$MobileIconGroup NR_5G_PLUS_USC;
    public static final SignalIcon$MobileIconGroup NR_5G_TMO;
    public static final SignalIcon$MobileIconGroup NR_5G_TMO_UC;
    public static final SignalIcon$MobileIconGroup NR_5G_USC;
    public static final SignalIcon$MobileIconGroup NR_5G_VZW;
    public static final SignalIcon$MobileIconGroup NR_5G_VZW_UWB;
    public static final SignalIcon$MobileIconGroup ONE_X;
    public static final SignalIcon$MobileIconGroup ONE_X_CHN;
    public static final SignalIcon$MobileIconGroup ONE_X_VZW;
    public static final SignalIcon$MobileIconGroup THREE_G;
    public static final SignalIcon$MobileIconGroup THREE_G_CHN;
    public static final SignalIcon$MobileIconGroup THREE_G_KT;
    public static final SignalIcon$MobileIconGroup THREE_G_PLUS;
    public static final SignalIcon$MobileIconGroup THREE_G_PLUS_CHN;
    public static final SignalIcon$MobileIconGroup THREE_G_TMO;
    public static final SignalIcon$MobileIconGroup THREE_G_VZW;
    public static final SignalIcon$MobileIconGroup TWO_G;
    public static final SignalIcon$MobileIconGroup TWO_G_CHN;
    public static final SignalIcon$MobileIconGroup UNKNOWN;
    public static final SignalIcon$MobileIconGroup WFC;

    static {
        int[] iArr = {R.drawable.stat_sys_data_no_inout, R.drawable.stat_sys_data_in, R.drawable.stat_sys_data_out, R.drawable.stat_sys_data_inout};
        MOBILE_DATA_ACTIVITY_ICONS = iArr;
        int[] iArr2 = {R.drawable.stat_sys_data_w14_no_inout, R.drawable.stat_sys_data_w14_in, R.drawable.stat_sys_data_w14_out, R.drawable.stat_sys_data_w14_inout};
        int[] iArr3 = {R.drawable.stat_sys_data_no_inout_chn, R.drawable.stat_sys_data_in_chn, R.drawable.stat_sys_data_out_chn, R.drawable.stat_sys_data_inout_chn};
        int[] iArr4 = {0, R.drawable.stat_sys_data_in_anim_att, R.drawable.stat_sys_data_out_anim_att, R.drawable.stat_sys_data_inout_anim_att};
        int[] iArr5 = {0, R.drawable.stat_sys_data_in_anim_5g_att, R.drawable.stat_sys_data_out_anim_5g_att, R.drawable.stat_sys_data_inout_anim_5g_att};
        int[] iArr6 = {R.drawable.stat_sys_data_no_inout_4g_plus_chn, R.drawable.stat_sys_data_in_4g_plus_chn, R.drawable.stat_sys_data_out_4g_plus_chn, R.drawable.stat_sys_data_inout_4g_plus_chn};
        int[] iArr7 = {R.drawable.stat_sys_data_no_inout_lte_plus_kt, R.drawable.stat_sys_data_in_lte_plus_kt, R.drawable.stat_sys_data_out_lte_plus_kt, R.drawable.stat_sys_data_inout_lte_plus_kt};
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup = new SignalIcon$MobileIconGroup("CARRIER_NETWORK_CHANGE", R.string.carrier_network_change_mode, 0);
        CARRIER_NETWORK_CHANGE = signalIcon$MobileIconGroup;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup2 = new SignalIcon$MobileIconGroup("3G", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_3g);
        THREE_G = signalIcon$MobileIconGroup2;
        THREE_G_KT = new SignalIcon$MobileIconGroup("3G_KT", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_3g_kt, iArr);
        THREE_G_CHN = new SignalIcon$MobileIconGroup("3G_CHN", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_3g_chn, iArr3);
        THREE_G_TMO = new SignalIcon$MobileIconGroup("3G_TMO", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_3g_tmo);
        THREE_G_VZW = new SignalIcon$MobileIconGroup("3G_VZW", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_3g_vzw, null);
        THREE_G_PLUS = new SignalIcon$MobileIconGroup("3G+", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_3g_plus, iArr);
        THREE_G_PLUS_CHN = new SignalIcon$MobileIconGroup("3G+_CHN", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_3g_plus_chn, iArr3);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup3 = new SignalIcon$MobileIconGroup("WFC", 0, 0);
        WFC = signalIcon$MobileIconGroup3;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup4 = new SignalIcon$MobileIconGroup("Unknown", 0, 0, null);
        UNKNOWN = signalIcon$MobileIconGroup4;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup5 = new SignalIcon$MobileIconGroup(ImsProfile.TIMER_NAME_E, R.string.data_connection_edge, R.drawable.stat_sys_data_connected_e);
        E = signalIcon$MobileIconGroup5;
        E_VZW = new SignalIcon$MobileIconGroup("E_VZW", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_e_vzw, null);
        E_CHN = new SignalIcon$MobileIconGroup("E_CHN", R.string.data_connection_3g, R.drawable.stat_sys_data_connected_e_chn, iArr3);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup6 = new SignalIcon$MobileIconGroup("1X", R.string.data_connection_cdma, R.drawable.stat_sys_data_connected_1x);
        ONE_X = signalIcon$MobileIconGroup6;
        ONE_X_VZW = new SignalIcon$MobileIconGroup("1X_VZW", R.string.data_connection_cdma, R.drawable.stat_sys_data_connected_1x_vzw, null);
        ONE_X_CHN = new SignalIcon$MobileIconGroup("1X_CHN", R.string.data_connection_cdma, R.drawable.stat_sys_data_connected_1x_chn, iArr3);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup7 = new SignalIcon$MobileIconGroup(ImsProfile.TIMER_NAME_G, R.string.data_connection_gprs, R.drawable.stat_sys_data_connected_g);
        G = signalIcon$MobileIconGroup7;
        G_VZW = new SignalIcon$MobileIconGroup("G_VZW", R.string.data_connection_gprs, R.drawable.stat_sys_data_connected_g_vzw, null);
        G_CHN = new SignalIcon$MobileIconGroup("G_CHN", R.string.data_connection_gprs, R.drawable.stat_sys_data_connected_g_chn, iArr3);
        TWO_G = new SignalIcon$MobileIconGroup("2G", R.string.data_connection_cdma, R.drawable.stat_sys_data_connected_2g, iArr);
        new SignalIcon$MobileIconGroup("2G_KT", R.string.data_connection_cdma, R.drawable.stat_sys_data_connected_2g_kt, iArr);
        TWO_G_CHN = new SignalIcon$MobileIconGroup("2G_CHN", R.string.data_connection_cdma, R.drawable.stat_sys_data_connected_2g_chn, iArr3);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup8 = new SignalIcon$MobileIconGroup(ImsProfile.TIMER_NAME_H, R.string.data_connection_3_5g, R.drawable.stat_sys_data_connected_h);
        H = signalIcon$MobileIconGroup8;
        H_VZW = new SignalIcon$MobileIconGroup("H_VZW", R.string.data_connection_3_5g, R.drawable.stat_sys_data_connected_h_vzw, null);
        H_CHN = new SignalIcon$MobileIconGroup("H_CHN", R.string.data_connection_3_5g, R.drawable.stat_sys_data_connected_h_chn, iArr3);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup9 = new SignalIcon$MobileIconGroup("H+", R.string.data_connection_3_5g_plus, R.drawable.stat_sys_data_connected_h_plus);
        H_PLUS = signalIcon$MobileIconGroup9;
        H_PLUS_VZW = new SignalIcon$MobileIconGroup("H+_VZW", R.string.data_connection_3_5g_plus, R.drawable.stat_sys_data_connected_h_plus_vzw, null);
        H_PLUS_CHN = new SignalIcon$MobileIconGroup("H+_CHN", R.string.data_connection_3_5g_plus, R.drawable.stat_sys_data_connected_h_plus_chn, iArr3);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup10 = new SignalIcon$MobileIconGroup("4G", R.string.data_connection_4g, R.drawable.stat_sys_data_connected_4g, iArr2);
        FOUR_G = signalIcon$MobileIconGroup10;
        FOUR_G_ATT = new SignalIcon$MobileIconGroup("4G_ATT", R.string.data_connection_4g, R.drawable.stat_sys_data_connected_4g_att, iArr4);
        FOUR_G_TMO = new SignalIcon$MobileIconGroup("4G_TMO", R.string.data_connection_4g, R.drawable.stat_sys_data_connected_4g_tmo);
        FOUR_G_USC = new SignalIcon$MobileIconGroup("4G_USC", R.string.data_connection_4g, R.drawable.stat_sys_data_connected_4g_uscc, iArr);
        FOUR_G_VZW = new SignalIcon$MobileIconGroup("4G_VZW", R.string.data_connection_4g, R.drawable.stat_sys_data_connected_4g_vzw, null);
        FOUR_G_CHN = new SignalIcon$MobileIconGroup("4G_CHN", R.string.data_connection_4g, R.drawable.stat_sys_data_connected_4g_chn, iArr3);
        FOUR_G_LTE_LTN = new SignalIcon$MobileIconGroup("4G_LTE_LTN", R.string.data_connection_4g, R.drawable.stat_sys_data_connected_4g_lte_ltn);
        FOUR_HALF_G = new SignalIcon$MobileIconGroup("4.5G", R.string.data_connection_4g_plus, R.drawable.stat_sys_data_connected_4_half_g);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup11 = new SignalIcon$MobileIconGroup("4G+", R.string.data_connection_4g_plus, R.drawable.stat_sys_data_connected_4g_plus);
        FOUR_G_PLUS = signalIcon$MobileIconGroup11;
        FOUR_G_PLUS_CHN = new SignalIcon$MobileIconGroup("4G+_CHN", R.string.data_connection_4g_plus, R.drawable.stat_sys_data_connected_4g_plus_chn, iArr6);
        FOUR_HALF_G_AMX = new SignalIcon$MobileIconGroup("4.5G_AMX", R.string.data_connection_4g_plus, R.drawable.stat_sys_data_fully_connected_4_half_g_amx);
        FOUR_HALF_G_PLUS_AMX = new SignalIcon$MobileIconGroup("4.5G_Plus_AMX", R.string.data_connection_4g_plus, R.drawable.stat_sys_data_fully_connected_4_half_g_plus_amx);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup12 = new SignalIcon$MobileIconGroup("LTE", R.string.data_connection_lte, R.drawable.stat_sys_data_connected_lte);
        LTE = signalIcon$MobileIconGroup12;
        LTE_KT = new SignalIcon$MobileIconGroup("LTE_KT", R.string.data_connection_lte, R.drawable.stat_sys_data_connected_lte_kt, iArr);
        LTE_ATT = new SignalIcon$MobileIconGroup("LTE_ATT", R.string.data_connection_lte, R.drawable.stat_sys_data_connected_lte_att, iArr4);
        LTE_TMO = new SignalIcon$MobileIconGroup("LTE_TMO", R.string.data_connection_lte, R.drawable.stat_sys_data_connected_lte_tmo);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup13 = new SignalIcon$MobileIconGroup("LTE+", R.string.data_connection_lte_plus, R.drawable.stat_sys_data_connected_lte_plus);
        LTE_PLUS = signalIcon$MobileIconGroup13;
        LTE_PLUS_KT = new SignalIcon$MobileIconGroup("LTE_PLUS_KT", R.string.data_connection_lte_plus, R.drawable.stat_sys_data_connected_lte_plus_kt, iArr7);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup14 = new SignalIcon$MobileIconGroup("4G LTE", R.string.data_connection_4g_lte, R.drawable.ic_4g_lte_mobiledata);
        FOUR_G_LTE = signalIcon$MobileIconGroup14;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup15 = new SignalIcon$MobileIconGroup("4G LTE+", R.string.data_connection_4g_lte_plus, R.drawable.ic_4g_lte_plus_mobiledata);
        FOUR_G_LTE_PLUS = signalIcon$MobileIconGroup15;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup16 = new SignalIcon$MobileIconGroup("5Ge", R.string.data_connection_5ge_html, R.drawable.ic_5g_e_mobiledata, null);
        LTE_CA_5G_E = signalIcon$MobileIconGroup16;
        NR_5G_E_ATT = new SignalIcon$MobileIconGroup("5Ge_ATT", R.string.data_connection_5ge_html, R.drawable.stat_sys_data_connected_5ge_att, iArr5);
        NR_5G_AVAILABLE = new SignalIcon$MobileIconGroup("5G_Available", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_available);
        NR_5G_AVAILABLE_KT = new SignalIcon$MobileIconGroup("5G_Available_KT", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_available_kt, iArr);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup17 = new SignalIcon$MobileIconGroup("5G", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_one_shaped);
        NR_5G = signalIcon$MobileIconGroup17;
        NR_5G_CONNECTED = new SignalIcon$MobileIconGroup("5G_Connected", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g);
        NR_5G_CONNECTED_KT = new SignalIcon$MobileIconGroup("5G_Connected_KT", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_connected_kt, iArr);
        NR_5G_ATT = new SignalIcon$MobileIconGroup("5G_ATT", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_att, iArr5);
        NR_5G_TMO = new SignalIcon$MobileIconGroup("5G_TMO", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_tmo, null);
        NR_5G_USC = new SignalIcon$MobileIconGroup("5G_USC", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_uscc, null);
        NR_5G_VZW = new SignalIcon$MobileIconGroup("5G_VZW", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_vzw, null);
        NR_5G_CHN = new SignalIcon$MobileIconGroup("5G_OneShaped_CHN", R.string.data_connection_5g, R.drawable.stat_sys_data_connected_5g_one_shaped_chn, iArr3);
        NR_5GA_CHN = new SignalIcon$MobileIconGroup("5GA_CHN", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5ga_chn, iArr3);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup18 = new SignalIcon$MobileIconGroup("5G_PLUS", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5g_plus_one_shaped);
        NR_5G_PLUS = signalIcon$MobileIconGroup18;
        NR_5G_CONNECTED_PLUS = new SignalIcon$MobileIconGroup("5G+_Connected", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5g_plus_connected);
        NR_5G_PLUS_USC = new SignalIcon$MobileIconGroup("5G+_USC", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5g_plus_uscc, null);
        NR_5G_PLUS_ATT = new SignalIcon$MobileIconGroup("5G+_ATT", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5g_plus_att, iArr5);
        NR_5G_TMO_UC = new SignalIcon$MobileIconGroup("5G+_TMO", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5g_uc_tmo, null);
        NR_5G_VZW_UWB = new SignalIcon$MobileIconGroup("5G_UWB_VZW", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5g_uwb_vzw, null);
        NR_5G_ENLARGED_PLUS = new SignalIcon$MobileIconGroup("5G+_Enlarge", R.string.data_connection_5g_plus, R.drawable.stat_sys_data_connected_5g_plus_enlarged, null);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup19 = new SignalIcon$MobileIconGroup("DataDisabled", R.string.cell_data_off_content_description, 0);
        DATA_DISABLED = signalIcon$MobileIconGroup19;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup20 = new SignalIcon$MobileIconGroup("NotDefaultData", R.string.not_default_data_content_description, 0, null);
        NOT_DEFAULT_DATA = signalIcon$MobileIconGroup20;
        CARRIER_MERGED_WIFI = new SignalIcon$MobileIconGroup("CWF", R.string.data_connection_carrier_wifi, R.drawable.ic_carrier_wifi);
        HashMap hashMap = new HashMap();
        ICON_NAME_TO_ICON = hashMap;
        hashMap.put("carrier_network_change", signalIcon$MobileIconGroup);
        hashMap.put("3g", signalIcon$MobileIconGroup2);
        hashMap.put("wfc", signalIcon$MobileIconGroup3);
        hashMap.put("unknown", signalIcon$MobileIconGroup4);
        hashMap.put("e", signalIcon$MobileIconGroup5);
        hashMap.put("1x", signalIcon$MobileIconGroup6);
        hashMap.put("g", signalIcon$MobileIconGroup7);
        hashMap.put("h", signalIcon$MobileIconGroup8);
        hashMap.put("h+", signalIcon$MobileIconGroup9);
        hashMap.put("4g", signalIcon$MobileIconGroup10);
        hashMap.put("4g+", signalIcon$MobileIconGroup11);
        hashMap.put("4glte", signalIcon$MobileIconGroup14);
        hashMap.put("4glte+", signalIcon$MobileIconGroup15);
        hashMap.put("5ge", signalIcon$MobileIconGroup16);
        hashMap.put("lte", signalIcon$MobileIconGroup12);
        hashMap.put("lte+", signalIcon$MobileIconGroup13);
        hashMap.put("5g", signalIcon$MobileIconGroup17);
        hashMap.put("5g_plus", signalIcon$MobileIconGroup18);
        hashMap.put("datadisable", signalIcon$MobileIconGroup19);
        hashMap.put("notdefaultdata", signalIcon$MobileIconGroup20);
        MOBILE_CALL_STRENGTH_ICONS = new int[]{R.drawable.ic_mobile_call_strength_0, R.drawable.ic_mobile_call_strength_1, R.drawable.ic_mobile_call_strength_2, R.drawable.ic_mobile_call_strength_3, R.drawable.ic_mobile_call_strength_4};
    }
}
