package com.android.systemui.flags;

import com.android.systemui.R;
import com.samsung.android.knox.custom.IKnoxCustomManager;
import com.samsung.android.knox.license.KnoxEnterpriseLicenseManager;
import com.samsung.android.knox.net.vpn.VpnErrorValues;
import com.sec.ims.volte2.data.VolteConstants;

/* compiled from: qb/87000731 7862a37e62df4d72b2921859baacdc80ea0c935793521606c8e11db53cc87e4f */
/* loaded from: classes.dex */
public final class Flags {
    public static final ReleasedFlag ALWAYS_SHOW_HOME_CONTROLS_ON_DREAMS;
    public static final ReleasedFlag ANIMATED_NOTIFICATION_SHADE_INSETS;
    public static final ReleasedFlag APP_PANELS_ALL_APPS_ALLOWED;
    public static final ReleasedFlag APP_PANELS_REMOVE_APPS_ALLOWED;
    public static final ResourceBooleanFlag BATTERY_SHIELD_ICON;
    public static final ResourceBooleanFlag BOUNCER_USER_SWITCHER;
    public static final SysPropBooleanFlag BUILDER_EXTRAS_OVERRIDE;
    public static final ResourceBooleanFlag CHARGING_RIPPLE;
    public static final ReleasedFlag CONTROLS_MANAGEMENT_NEW_FLOWS;
    public static final ReleasedFlag CUSTOMIZABLE_LOCK_SCREEN_QUICK_AFFORDANCES;
    public static final UnreleasedFlag ENABLE_DARK_VIGNETTE_WHEN_FOLDING;
    public static final SysPropBooleanFlag ENABLE_FLING_TO_DISMISS_BUBBLE;
    public static final SysPropBooleanFlag ENABLE_FLING_TO_DISMISS_PIP;
    public static final ReleasedFlag ENABLE_FONT_SCALING_TILE;
    public static final SysPropBooleanFlag ENABLE_PIP_APP_ICON_OVERLAY;
    public static final SysPropBooleanFlag ENABLE_PIP_KEEP_CLEAR_ALGORITHM;
    public static final SysPropBooleanFlag ENABLE_PIP_SIZE_LARGE_SCREEN;
    public static final UnreleasedFlag ENABLE_UNFOLD_STATUS_BAR_ANIMATIONS;
    public static final ReleasedFlag ENABLE_USI_BATTERY_NOTIFICATIONS;
    public static final ReleasedFlag FALSING_OFF_FOR_UNFOLDED;
    public static final ResourceBooleanFlag FULL_SCREEN_USER_SWITCHER;
    public static final SysPropBooleanFlag HIDE_NAVBAR_WINDOW;
    public static final Flags INSTANCE = new Flags();
    public static final ReleasedFlag KEYGUARD_TALKBACK_FIX;
    public static final ReleasedFlag LARGE_SHADE_GRANULAR_ALPHA_INTERPOLATION;
    public static final ReleasedFlag LOAD_NOTIFICATIONS_BEFORE_THE_USER_SWITCH_IS_COMPLETE;
    public static final ResourceBooleanFlag LOCKSCREEN_CUSTOM_CLOCKS;
    public static final SysPropBooleanFlag LOCKSCREEN_LIVE_WALLPAPER;
    public static final ReleasedFlag LOCKSCREEN_WITHOUT_SECURE_LOCK_WHEN_DREAMING;
    public static final ReleasedFlag LOCK_SCREEN_LONG_PRESS_ENABLED;
    public static final ReleasedFlag MEDIA_EXPLICIT_INDICATOR;
    public static final ReleasedFlag MEDIA_MUTE_AWAIT;
    public static final ReleasedFlag MEDIA_NEARBY_DEVICES;
    public static final ReleasedFlag MEDIA_RESUME_PROGRESS;
    public static final ReleasedFlag MEDIA_TAP_TO_TRANSFER;
    public static final ReleasedFlag MEDIA_TAP_TO_TRANSFER_DISMISS_GESTURE;
    public static final ReleasedFlag MEDIA_TTT_RECEIVER_SUCCESS_RIPPLE;
    public static final ResourceBooleanFlag MONET;
    public static final ReleasedFlag MONOCHROMATIC_THEME;
    public static final ReleasedFlag NEW_BACK_AFFORDANCE;
    public static final ReleasedFlag NEW_LIGHT_BAR_LOGIC;
    public static final ReleasedFlag NEW_STATUS_BAR_MOBILE_ICONS;
    public static final ReleasedFlag NEW_STATUS_BAR_WIFI_ICON;
    public static final ReleasedFlag NEW_UNLOCK_SWIPE_ANIMATION;
    public static final ReleasedFlag NOTE_TASKS;
    public static final ResourceBooleanFlag NOTIFICATION_DRAG_TO_CONTENTS;
    public static final ReleasedFlag NO_HUN_FOR_OLD_WHEN;
    public static final ReleasedFlag ONGOING_CALL_IN_IMMERSIVE;
    public static final ReleasedFlag ONGOING_CALL_IN_IMMERSIVE_CHIP_TAP;
    public static final ReleasedFlag ONGOING_CALL_STATUS_BAR_CHIP;
    public static final ReleasedFlag PLUG_IN_STATUS_BAR_CHIP;
    public static final ReleasedFlag POWER_MENU_LITE;
    public static final ReleasedFlag QS_SECONDARY_DATA_SUB_INFO;
    public static final ResourceBooleanFlag QS_USER_DETAIL_SHORTCUT;
    public static final ReleasedFlag REVAMPED_WALLPAPER_UI;
    public static final ReleasedFlag SCREENSHOT_APP_CLIPS;
    public static final ReleasedFlag SHORTCUT_LIST_SEARCH_LAYOUT;
    public static final ReleasedFlag SIMPLIFIED_APPEAR_FRACTION;
    public static final SysPropBooleanFlag SMARTSPACE_DATE_WEATHER_DECOUPLED;
    public static final ReleasedFlag STEP_CLOCK_ANIMATION;
    public static final UnreleasedFlag TEAMFOOD;
    public static final ReleasedFlag TRACKPAD_GESTURE_COMMON;
    public static final ReleasedFlag TRACK_STYLUS_EVER_USED;
    public static final ReleasedFlag UDFPS_ELLIPSE_DETECTION;
    public static final ReleasedFlag UDFPS_NEW_TOUCH_DETECTION;
    public static final ReleasedFlag USE_APP_PANELS;
    public static final ReleasedFlag WALLPAPER_FULLSCREEN_PREVIEW;
    public static final SysPropBooleanFlag WALLPAPER_MULTI_CROP;
    public static final SysPropBooleanFlag WM_ALWAYS_ENFORCE_PREDICTIVE_BACK;
    public static final SysPropBooleanFlag WM_BUBBLE_BAR;
    public static final SysPropBooleanFlag WM_CAPTION_ON_SHELL;
    public static final SysPropBooleanFlag WM_DESKTOP_WINDOWING;
    public static final SysPropBooleanFlag WM_DESKTOP_WINDOWING_2;
    public static final UnreleasedFlag WM_ENABLE_PARTIAL_SCREEN_SHARING;
    public static final UnreleasedFlag WM_ENABLE_PARTIAL_SCREEN_SHARING_ENTERPRISE_POLICIES;
    public static final SysPropBooleanFlag WM_ENABLE_PREDICTIVE_BACK;
    public static final SysPropBooleanFlag WM_ENABLE_PREDICTIVE_BACK_ANIM;
    public static final SysPropBooleanFlag WM_ENABLE_SHELL_TRANSITIONS;
    public static final ReleasedFlag ZJ_285570694_LOCKSCREEN_TRANSITION_FROM_AOD;

    static {
        FlagsFactory flagsFactory = FlagsFactory.INSTANCE;
        TEAMFOOD = FlagsFactory.unreleasedFlag$default(flagsFactory, 1, false, 12);
        FlagsFactory.unreleasedFlag(103);
        FlagsFactory.unreleasedFlag(105);
        FlagsFactory.unreleasedFlag(106);
        NOTIFICATION_DRAG_TO_CONTENTS = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 108, R.bool.config_notificationToContents, "notification_drag_to_contents");
        FlagsFactory.unreleasedFlag(111);
        NEW_LIGHT_BAR_LOGIC = FlagsFactory.releasedFlag$default(flagsFactory, 279735475, "new_light_bar_logic");
        FlagsFactory.unreleasedFlag(119);
        SIMPLIFIED_APPEAR_FRACTION = FlagsFactory.releasedFlag$default(flagsFactory, 259395680, "simplified_appear_fraction");
        NO_HUN_FOR_OLD_WHEN = FlagsFactory.releasedFlag$default(flagsFactory, 118, "no_hun_for_old_when");
        FlagsFactory.unreleasedFlag(174148361);
        LOAD_NOTIFICATIONS_BEFORE_THE_USER_SWITCH_IS_COMPLETE = FlagsFactory.releasedFlag$default(flagsFactory, 278873737, "load_notifications_before_the_user_switch_is_complete");
        FlagsFactory.unreleasedFlag(271161129);
        ANIMATED_NOTIFICATION_SHADE_INSETS = FlagsFactory.releasedFlag$default(flagsFactory, 270682168, "animated_notification_shade_insets");
        FlagsFactory.unreleasedFlag(268005230);
        BUILDER_EXTRAS_OVERRIDE = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, 128, "persist.sysui.notification.builder_extras_override", false);
        NEW_UNLOCK_SWIPE_ANIMATION = FlagsFactory.releasedFlag$default(flagsFactory, 202, "new_unlock_swipe_animation");
        CHARGING_RIPPLE = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 203, R.bool.flag_charging_ripple, "charging_ripple");
        BOUNCER_USER_SWITCHER = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 204, R.bool.config_enableBouncerUserSwitcher, "bouncer_user_switcher");
        LOCKSCREEN_CUSTOM_CLOCKS = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 207, R.bool.config_enableLockScreenCustomClocks, "lockscreen_custom_clocks");
        LOCKSCREEN_WITHOUT_SECURE_LOCK_WHEN_DREAMING = FlagsFactory.releasedFlag$default(flagsFactory, 208, "lockscreen_without_secure_lock_when_dreaming");
        STEP_CLOCK_ANIMATION = FlagsFactory.releasedFlag$default(flagsFactory, IKnoxCustomManager.Stub.TRANSACTION_getWifiState, "step_clock_animation");
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_addAutoCallNumber);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_removeAutoCallNumber);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_getAutoCallNumberDelay);
        CUSTOMIZABLE_LOCK_SCREEN_QUICK_AFFORDANCES = FlagsFactory.releasedFlag$default(flagsFactory, IKnoxCustomManager.Stub.TRANSACTION_getAutoCallNumberAnswerMode, "customizable_lock_screen_quick_affordances");
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_setAutoCallPickupState);
        FlagsFactory.unreleasedFlag(220);
        FlagsFactory.unreleasedFlag(221);
        REVAMPED_WALLPAPER_UI = FlagsFactory.releasedFlag$default(flagsFactory, 222, "revamped_wallpaper_ui");
        String str = "auto_pin_confirmation";
        FlagsFactory.flagMap.put("auto_pin_confirmation", new ReleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_setUsbConnectionType, str, str, false, false, 16, null));
        FALSING_OFF_FOR_UNFOLDED = FlagsFactory.releasedFlag$default(flagsFactory, IKnoxCustomManager.Stub.TRANSACTION_getUsbConnectionType, "falsing_off_for_unfolded");
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_getUsbConnectionTypeInternal);
        WALLPAPER_FULLSCREEN_PREVIEW = FlagsFactory.releasedFlag$default(flagsFactory, IKnoxCustomManager.Stub.TRANSACTION_setForceAutoShutDownState, "wallpaper_fullscreen_preview");
        LOCK_SCREEN_LONG_PRESS_ENABLED = FlagsFactory.releasedFlag$default(flagsFactory, IKnoxCustomManager.Stub.TRANSACTION_getForceAutoShutDownState, "lock_screen_long_press_enabled");
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_setBrightness);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_removeShortcut);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_addWidget);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_removeWidget);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_deleteHomeScreenPage);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_setAppsButtonState);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_getAppsButtonState);
        FlagsFactory.unreleasedFlag(IKnoxCustomManager.Stub.TRANSACTION_setFavoriteApp);
        KEYGUARD_TALKBACK_FIX = FlagsFactory.releasedFlag$default(flagsFactory, IKnoxCustomManager.Stub.TRANSACTION_removeFavoriteApp, "keyguard_talkback_fix");
        POWER_MENU_LITE = FlagsFactory.releasedFlag$default(flagsFactory, 300, "power_menu_lite");
        FlagsFactory.releasedFlag$default(flagsFactory, 401, "smartspace_shared_element_transition_enabled");
        SMARTSPACE_DATE_WEATHER_DECOUPLED = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, 403, "persist.sysui.ss.dw_decoupled", true);
        FlagsFactory.releasedFlag$default(flagsFactory, 404, "hide_smartspace_on_dream_overlay");
        FlagsFactory.releasedFlag$default(flagsFactory, 405, "show_weather_complication_on_dream_overlay");
        FlagsFactory.resourceBooleanFlag$default(flagsFactory, 502, R.bool.flag_conversations, "people_tile");
        QS_USER_DETAIL_SHORTCUT = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 503, R.bool.flag_lockscreen_qs_user_detail_shortcut, "qs_user_detail_shortcut");
        FlagsFactory.unreleasedFlag(504);
        FlagsFactory.unreleasedFlag(505);
        FULL_SCREEN_USER_SWITCHER = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 506, R.bool.config_enableFullscreenUserSwitcher, "full_screen_user_switcher");
        QS_SECONDARY_DATA_SUB_INFO = FlagsFactory.releasedFlag$default(flagsFactory, 508, "qs_secondary_data_sub_info");
        ENABLE_FONT_SCALING_TILE = FlagsFactory.releasedFlag$default(flagsFactory, 509, "enable_font_scaling_tile");
        FlagsFactory.unreleasedFlag(510);
        NEW_STATUS_BAR_MOBILE_ICONS = FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.NOT_ACCEPTABLE2, "new_status_bar_mobile_icons");
        NEW_STATUS_BAR_WIFI_ICON = FlagsFactory.releasedFlag$default(flagsFactory, 607, "new_status_bar_wifi_icon");
        FlagsFactory.unreleasedFlag(608);
        FlagsFactory.unreleasedFlag(609);
        BATTERY_SHIELD_ICON = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 610, R.bool.flag_battery_shield_icon, "battery_shield_icon");
        FlagsFactory.unreleasedFlag(611);
        PLUG_IN_STATUS_BAR_CHIP = FlagsFactory.releasedFlag$default(flagsFactory, 265892345, "plug_in_status_bar_chip");
        FlagsFactory.unreleasedFlag(612);
        ONGOING_CALL_STATUS_BAR_CHIP = FlagsFactory.releasedFlag$default(flagsFactory, KnoxEnterpriseLicenseManager.ERROR_LICENSE_DEACTIVATED, "ongoing_call_status_bar_chip");
        ONGOING_CALL_IN_IMMERSIVE = FlagsFactory.releasedFlag$default(flagsFactory, 701, "ongoing_call_in_immersive");
        ONGOING_CALL_IN_IMMERSIVE_CHIP_TAP = FlagsFactory.releasedFlag$default(flagsFactory, 702, "ongoing_call_in_immersive_chip_tap");
        MONET = FlagsFactory.resourceBooleanFlag$default(flagsFactory, 800, R.bool.flag_monet, "monet");
        FlagsFactory.unreleasedFlag(801);
        FlagsFactory.unreleasedFlag(VpnErrorValues.ERROR_STORING_PROXY_PASSWORD);
        MONOCHROMATIC_THEME = FlagsFactory.releasedFlag$default(flagsFactory, VpnErrorValues.ERROR_INVALID_PROXY_CONFIGURATION, "monochromatic");
        MEDIA_TAP_TO_TRANSFER = FlagsFactory.releasedFlag$default(flagsFactory, 900, "media_tap_to_transfer");
        FlagsFactory.unreleasedFlag(901);
        MEDIA_NEARBY_DEVICES = FlagsFactory.releasedFlag$default(flagsFactory, 903, "media_nearby_devices");
        MEDIA_MUTE_AWAIT = FlagsFactory.releasedFlag$default(flagsFactory, 904, "media_mute_await");
        FlagsFactory.unreleasedFlag(905);
        FlagsFactory.unreleasedFlag(906);
        FlagsFactory.releasedFlag$default(flagsFactory, 907, "umo_surface_ripple");
        FlagsFactory.releasedFlag$default(flagsFactory, 909, "umo_turbulence_noise");
        MEDIA_TTT_RECEIVER_SUCCESS_RIPPLE = FlagsFactory.releasedFlag$default(flagsFactory, 910, "media_ttt_receiver_success_ripple");
        MEDIA_EXPLICIT_INDICATOR = FlagsFactory.releasedFlag$default(flagsFactory, 911, "media_explicit_indicator");
        MEDIA_TAP_TO_TRANSFER_DISMISS_GESTURE = FlagsFactory.releasedFlag$default(flagsFactory, 912, "media_ttt_dismiss_gesture");
        FlagsFactory.unreleasedFlag(913);
        FlagsFactory.releasedFlag$default(flagsFactory, 914, "media_recommendation_card_update");
        MEDIA_RESUME_PROGRESS = FlagsFactory.releasedFlag$default(flagsFactory, 915, "media_resume_progress");
        FlagsFactory.unreleasedFlag(916);
        FlagsFactory.unreleasedFlag(917);
        FlagsFactory.releasedFlag$default(flagsFactory, 1000, "simulate_dock_through_charging");
        FlagsFactory.releasedFlag$default(flagsFactory, 1002, "rounded_box_ripple");
        FlagsFactory.releasedFlag$default(flagsFactory, 1003, "show_lowlight_on_direct_boot");
        ALWAYS_SHOW_HOME_CONTROLS_ON_DREAMS = FlagsFactory.releasedFlag$default(flagsFactory, 1006, "always_show_home_controls_on_dreams");
        WM_ENABLE_SHELL_TRANSITIONS = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, 1100, "persist.wm.debug.shell_transit", true);
        WM_ENABLE_PARTIAL_SCREEN_SHARING = FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.CALL_SESSION_TERMINATED);
        HIDE_NAVBAR_WINDOW = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_SESSION_TIMEOUT, "persist.wm.debug.hide_navbar_window", false);
        WM_DESKTOP_WINDOWING = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_STATUS_CONF_START_SESSION_FAILURE, "persist.wm.debug.desktop_mode", false);
        WM_CAPTION_ON_SHELL = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_STATUS_CONF_ADD_USER_TO_SESSION_FAILURE, "persist.wm.debug.caption_on_shell", false);
        ENABLE_FLING_TO_DISMISS_BUBBLE = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_REJECT_REASON_USR_BUSY_CS_CALL, "persist.wm.debug.fling_to_dismiss_bubble", true);
        ENABLE_FLING_TO_DISMISS_PIP = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_SWITCH_FAILURE, "persist.wm.debug.fling_to_dismiss_pip", true);
        ENABLE_PIP_KEEP_CLEAR_ALGORITHM = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_SWITCH_REJECTED, "persist.wm.debug.enable_pip_keep_clear_algorithm", true);
        WM_BUBBLE_BAR = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_HOLD_FAILED, "persist.wm.debug.bubble_bar", false);
        WM_DESKTOP_WINDOWING_2 = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_RESUME_FAILED, "persist.wm.debug.desktop_mode_2", false);
        WM_ENABLE_PARTIAL_SCREEN_SHARING_ENTERPRISE_POLICIES = FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.CALL_TEMP_UNAVAILABLE_415_CAUSE);
        ENABLE_PIP_SIZE_LARGE_SCREEN = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_INVITE_TIMEOUT, "persist.wm.debug.enable_pip_size_large_screen", true);
        ENABLE_PIP_APP_ICON_OVERLAY = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_END_REASON_IMS_DEREGISTRATION, "persist.wm.debug.enable_pip_app_icon_overlay", true);
        LOCKSCREEN_LIVE_WALLPAPER = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_ENDED_BY_NW_HANDOVER_BEFORE_100_TRYING, "persist.wm.debug.lockscreen_live_wallpaper", false);
        WALLPAPER_MULTI_CROP = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_TRANSFER_SUCCESS, "persist.wm.debug.wallpaper_multi_crop", false);
        WM_ENABLE_PREDICTIVE_BACK = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, 1200, "persist.wm.debug.predictive_back", true);
        WM_ENABLE_PREDICTIVE_BACK_ANIM = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.QOS_FAILURE, "persist.wm.debug.predictive_back_anim", true);
        WM_ALWAYS_ENFORCE_PREDICTIVE_BACK = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, VolteConstants.ErrorCode.QOS_NW_UNAWARE, "persist.wm.debug.predictive_back_always_enforce", false);
        NEW_BACK_AFFORDANCE = FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.QOS_INCALL_SUSPEND, "new_back_affordance");
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.QOS_INCALL_UNAWARE);
        FlagsFactory.unreleasedFlag(1205);
        FlagsFactory.unreleasedFlag(1206);
        FlagsFactory.sysPropBooleanFlag$default(flagsFactory, 1207, "persist.wm.debug.shade_allow_back_gesture", false);
        FlagsFactory.unreleasedFlag(1208);
        FlagsFactory.unreleasedFlag(1209);
        TRACKPAD_GESTURE_COMMON = FlagsFactory.releasedFlag$default(flagsFactory, 1210, "trackpad_gesture_common");
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.PPP_OPEN_FAILURE);
        FlagsFactory.releasedFlag$default(flagsFactory, 1303, "screenshot_detection");
        SCREENSHOT_APP_CLIPS = FlagsFactory.releasedFlag$default(flagsFactory, 1304, "screenshot_app_clips");
        FlagsFactory.releasedFlag$default(flagsFactory, 1400, "quick_tap_in_pcc");
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.RTP_TIME_OUT);
        FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.DATA_CONNECTION_LOST, "clipboard_remote_behavior");
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.RRC_CONNECTION_REJECT);
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.WIFI_CONNECTION_LOST);
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.FAILED_TO_GO_READY);
        NOTE_TASKS = FlagsFactory.releasedFlag$default(flagsFactory, 1900, "keycode_flag");
        USE_APP_PANELS = FlagsFactory.releasedFlag$default(flagsFactory, 2000, "use_app_panels");
        APP_PANELS_ALL_APPS_ALLOWED = FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_FORBIDDEN, "app_panels_all_apps_allowed");
        CONTROLS_MANAGEMENT_NEW_FLOWS = FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.MAKECALL_REG_FAILURE_TIMER_F, "controls_management_new_flows");
        APP_PANELS_REMOVE_APPS_ALLOWED = FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.MAKECALL_REG_FAILURE_REG_403, "app_panels_remove_apps_allowed");
        UDFPS_NEW_TOUCH_DETECTION = FlagsFactory.releasedFlag$default(flagsFactory, 2200, "udfps_new_touch_detection");
        UDFPS_ELLIPSE_DETECTION = FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_5XX_RESPONSE, "udfps_ellipse_detection");
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.CALL_TEMP_UNAVAILABLE_WITH_380_CAUSE);
        TRACK_STYLUS_EVER_USED = FlagsFactory.releasedFlag$default(flagsFactory, 2300, "track_stylus_ever_used");
        FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_FAILED, "enable_stylus_charging_ui");
        ENABLE_USI_BATTERY_NOTIFICATIONS = FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_FORBIDDEN_RSN_EXPIRED, "enable_usi_battery_notifications");
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.CALL_FORBIDDEN_RSN_GROUP_CALL_SERVICE_UNAVAILABLE);
        FlagsFactory.unreleasedFlag(2400);
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.REG_SSL_CERTIFICATE_FAILURE);
        FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.DNS_QUERY_RETRY_START);
        ENABLE_DARK_VIGNETTE_WHEN_FOLDING = FlagsFactory.unreleasedFlag(2700);
        ENABLE_UNFOLD_STATUS_BAR_ANIMATIONS = FlagsFactory.unreleasedFlag(VolteConstants.ErrorCode.SERVER_INTERNAL_ERROR_WTH_INCOMPATIBLE_DESTINATION);
        FlagsFactory.unreleasedFlag(2);
        SHORTCUT_LIST_SEARCH_LAYOUT = FlagsFactory.releasedFlag$default(flagsFactory, 2600, "shortcut_list_search_layout");
        FlagsFactory.unreleasedFlag(2601);
        FlagsFactory.unreleasedFlag(2603);
        LARGE_SHADE_GRANULAR_ALPHA_INTERPOLATION = FlagsFactory.releasedFlag$default(flagsFactory, 2602, "large_shade_granular_alpha_interpolation");
        FlagsFactory.unreleasedFlag(2805);
        FlagsFactory.releasedFlag$default(flagsFactory, VolteConstants.ErrorCode.CALL_BARRED_BY_NETWORK, "use_new_activity_starter");
        ZJ_285570694_LOCKSCREEN_TRANSITION_FROM_AOD = FlagsFactory.releasedFlag$default(flagsFactory, 2900, "zj_285570694_lockscreen_transition_from_aod");
        FlagsFactory.unreleasedFlag(3000);
        FlagsFactory.unreleasedFlag(283084712);
        FlagsFactory.unreleasedFlag(283447257);
        FlagsFactory.unreleasedFlag(283740863);
        FlagsFactory.unreleasedFlag(2900);
    }

    private Flags() {
    }
}
